// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/assignment.dart';
import 'api/chanakya.dart';
import 'api/cognitive.dart';
import 'api/commentary.dart';
import 'api/context.dart';
import 'api/history.dart';
import 'api/humanizer.dart';
import 'api/moves.dart';
import 'api/persona.dart';
import 'api/pgn_db.dart';
import 'api/puzzles.dart';
import 'api/simple.dart';
import 'api/state.dart';
import 'api/status.dart';
import 'api/tactics.dart';
import 'api/threats.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => 552122714;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_kingslayer_chess',
        ioDirectory: 'rust_core/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  MiddlegameResult crateApiCognitiveAnalyzeMiddlegame({
    required List<SavedGameUci> games,
    required ScotomaResult scotoma,
  });

  ScotomaResult crateApiCognitiveAnalyzeScotoma({
    required List<SavedGameUci> games,
  });

  ChanakyaWeeklySummary crateApiAssignmentAnalyzeSubmittedGameRust({
    required String pgnContent,
    required ScotomaResult scotoma,
  });

  List<String> crateApiThreatsAnalyzeTacticalThreats({
    required String fen,
    required bool isChess960,
  });

  (String, String) crateApiPgnDbClassifyOpeningEco({
    required List<String> movesSan,
  });

  bool crateApiPgnDbClearAllGames({required String dbPath});

  bool crateApiPgnDbClearAllStudies({required String dbPath});

  bool crateApiPgnDbDeleteGameFromDb({
    required String dbPath,
    required String id,
  });

  GameTerminationStatus crateApiStatusEvaluateGameStatus({
    required String fen,
    required bool isChess960,
  });

  PositionMetrics crateApiContextEvaluatePositionMetrics({
    required String fen,
    required int historyLength,
    required bool isChess960,
  });

  String crateApiPgnDbExportPgnWithHeaders({
    required PgnGameHeader header,
    required String annotatedPgn,
  });

  Future<GameIncidents> crateApiCognitiveGameIncidentsDefault();

  TacticsResult crateApiTacticsGenerateTacticsAnalysis({
    required String fen,
    required List<String> userUciMoves,
    required List<StockfishTacticLine> engineAlternatives,
    required bool isChess960,
  });

  List<String> crateApiMovesGetLegalDestinations({
    required String fen,
    required String square,
    required bool isChess960,
  });

  Future<Puzzle?> crateApiPuzzlesGetRandomPuzzle({
    required String dbPath,
    int? minRating,
    int? maxRating,
  });

  List<String> crateApiHistoryGetSanHistory({
    required String initialFen,
    required List<String> uciMoves,
    required bool isChess960,
  });

  List<String> crateApiThreatsGetThreatenedSquares({
    required String fen,
    required bool isChess960,
  });

  String crateApiSimpleGreet({required String name});

  String crateApiHumanizerHumanizeMoveRust({
    required String fenBefore,
    required String moveUci,
    required bool isChess960,
  });

  Future<void> crateApiSimpleInitApp();

  List<String> crateApiPgnDbLoadAllGamesFromDb({required String dbPath});

  List<PgnGameRecord> crateApiPgnDbLoadStudiesFromDb({required String dbPath});

  List<PgnGameRecord> crateApiPgnDbParsePgnDatabase({required String pgnText});

  ChanakyaRoutine crateApiAssignmentRecommendTasksRust({
    required int elo,
    required ScotomaResult scotoma,
    required List<int> completedTutorials,
  });

  void crateApiCommentaryResetCommentaryHistoryRust();

  bool crateApiPgnDbSaveGameToDb({
    required String dbPath,
    required String id,
    required String savedAt,
    required String jsonData,
  });

  bool crateApiPgnDbSaveStudyToDb({
    required String dbPath,
    required PgnGameRecord game,
  });

  Future<List<Puzzle>> crateApiPuzzlesSearchPuzzles({
    required String dbPath,
    String? theme,
    int? minRating,
    int? maxRating,
    int? limit,
  });

  String crateApiChanakyaSelectChanakyaMoveRust({
    required String fen,
    required List<ChanakyaCandidate> candidates,
    required ChanakyaScotoma scotoma,
    required ChanakyaPlaystyle playstyle,
    required int halfMoveCount,
    required double evalAbs,
    required bool isChess960,
  });

  String crateApiCommentarySelectCommentaryTemplateRust({
    required String quality,
    required String previousQuality,
    required String gamePhase,
    required double evalDiff,
    required bool hasFork,
    required bool hasPin,
    required bool hasHanging,
  });

  String crateApiPersonaSelectPersonaMoveRust({
    required String fen,
    required List<PersonaCandidate> candidates,
    required String avatarName,
    required bool isChess960,
    required int moveCount,
  });

  String? crateApiStateValidateAndApplyMove({
    required String currentFen,
    required String fromStr,
    required String toStr,
    required String promotionStr,
    required bool isChess960,
  });
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  MiddlegameResult crateApiCognitiveAnalyzeMiddlegame({
    required List<SavedGameUci> games,
    required ScotomaResult scotoma,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_saved_game_uci(games, serializer);
          sse_encode_box_autoadd_scotoma_result(scotoma, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_middlegame_result,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCognitiveAnalyzeMiddlegameConstMeta,
        argValues: [games, scotoma],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCognitiveAnalyzeMiddlegameConstMeta =>
      const TaskConstMeta(
        debugName: "analyze_middlegame",
        argNames: ["games", "scotoma"],
      );

  @override
  ScotomaResult crateApiCognitiveAnalyzeScotoma({
    required List<SavedGameUci> games,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_saved_game_uci(games, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_scotoma_result,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCognitiveAnalyzeScotomaConstMeta,
        argValues: [games],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCognitiveAnalyzeScotomaConstMeta =>
      const TaskConstMeta(debugName: "analyze_scotoma", argNames: ["games"]);

  @override
  ChanakyaWeeklySummary crateApiAssignmentAnalyzeSubmittedGameRust({
    required String pgnContent,
    required ScotomaResult scotoma,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(pgnContent, serializer);
          sse_encode_box_autoadd_scotoma_result(scotoma, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_chanakya_weekly_summary,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAssignmentAnalyzeSubmittedGameRustConstMeta,
        argValues: [pgnContent, scotoma],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAssignmentAnalyzeSubmittedGameRustConstMeta =>
      const TaskConstMeta(
        debugName: "analyze_submitted_game_rust",
        argNames: ["pgnContent", "scotoma"],
      );

  @override
  List<String> crateApiThreatsAnalyzeTacticalThreats({
    required String fen,
    required bool isChess960,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(fen, serializer);
          sse_encode_bool(isChess960, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiThreatsAnalyzeTacticalThreatsConstMeta,
        argValues: [fen, isChess960],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiThreatsAnalyzeTacticalThreatsConstMeta =>
      const TaskConstMeta(
        debugName: "analyze_tactical_threats",
        argNames: ["fen", "isChess960"],
      );

  @override
  (String, String) crateApiPgnDbClassifyOpeningEco({
    required List<String> movesSan,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_String(movesSan, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_record_string_string,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiPgnDbClassifyOpeningEcoConstMeta,
        argValues: [movesSan],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPgnDbClassifyOpeningEcoConstMeta =>
      const TaskConstMeta(
        debugName: "classify_opening_eco",
        argNames: ["movesSan"],
      );

  @override
  bool crateApiPgnDbClearAllGames({required String dbPath}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(dbPath, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 6)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiPgnDbClearAllGamesConstMeta,
        argValues: [dbPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPgnDbClearAllGamesConstMeta =>
      const TaskConstMeta(debugName: "clear_all_games", argNames: ["dbPath"]);

  @override
  bool crateApiPgnDbClearAllStudies({required String dbPath}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(dbPath, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiPgnDbClearAllStudiesConstMeta,
        argValues: [dbPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPgnDbClearAllStudiesConstMeta =>
      const TaskConstMeta(debugName: "clear_all_studies", argNames: ["dbPath"]);

  @override
  bool crateApiPgnDbDeleteGameFromDb({
    required String dbPath,
    required String id,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(dbPath, serializer);
          sse_encode_String(id, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 8)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiPgnDbDeleteGameFromDbConstMeta,
        argValues: [dbPath, id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPgnDbDeleteGameFromDbConstMeta =>
      const TaskConstMeta(
        debugName: "delete_game_from_db",
        argNames: ["dbPath", "id"],
      );

  @override
  GameTerminationStatus crateApiStatusEvaluateGameStatus({
    required String fen,
    required bool isChess960,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(fen, serializer);
          sse_encode_bool(isChess960, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 9)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_game_termination_status,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiStatusEvaluateGameStatusConstMeta,
        argValues: [fen, isChess960],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStatusEvaluateGameStatusConstMeta =>
      const TaskConstMeta(
        debugName: "evaluate_game_status",
        argNames: ["fen", "isChess960"],
      );

  @override
  PositionMetrics crateApiContextEvaluatePositionMetrics({
    required String fen,
    required int historyLength,
    required bool isChess960,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(fen, serializer);
          sse_encode_u_32(historyLength, serializer);
          sse_encode_bool(isChess960, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 10)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_position_metrics,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiContextEvaluatePositionMetricsConstMeta,
        argValues: [fen, historyLength, isChess960],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiContextEvaluatePositionMetricsConstMeta =>
      const TaskConstMeta(
        debugName: "evaluate_position_metrics",
        argNames: ["fen", "historyLength", "isChess960"],
      );

  @override
  String crateApiPgnDbExportPgnWithHeaders({
    required PgnGameHeader header,
    required String annotatedPgn,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_pgn_game_header(header, serializer);
          sse_encode_String(annotatedPgn, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 11)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiPgnDbExportPgnWithHeadersConstMeta,
        argValues: [header, annotatedPgn],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPgnDbExportPgnWithHeadersConstMeta =>
      const TaskConstMeta(
        debugName: "export_pgn_with_headers",
        argNames: ["header", "annotatedPgn"],
      );

  @override
  Future<GameIncidents> crateApiCognitiveGameIncidentsDefault() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_game_incidents,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCognitiveGameIncidentsDefaultConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCognitiveGameIncidentsDefaultConstMeta =>
      const TaskConstMeta(debugName: "game_incidents_default", argNames: []);

  @override
  TacticsResult crateApiTacticsGenerateTacticsAnalysis({
    required String fen,
    required List<String> userUciMoves,
    required List<StockfishTacticLine> engineAlternatives,
    required bool isChess960,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(fen, serializer);
          sse_encode_list_String(userUciMoves, serializer);
          sse_encode_list_stockfish_tactic_line(engineAlternatives, serializer);
          sse_encode_bool(isChess960, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 13)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_tactics_result,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTacticsGenerateTacticsAnalysisConstMeta,
        argValues: [fen, userUciMoves, engineAlternatives, isChess960],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTacticsGenerateTacticsAnalysisConstMeta =>
      const TaskConstMeta(
        debugName: "generate_tactics_analysis",
        argNames: ["fen", "userUciMoves", "engineAlternatives", "isChess960"],
      );

  @override
  List<String> crateApiMovesGetLegalDestinations({
    required String fen,
    required String square,
    required bool isChess960,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(fen, serializer);
          sse_encode_String(square, serializer);
          sse_encode_bool(isChess960, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 14)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiMovesGetLegalDestinationsConstMeta,
        argValues: [fen, square, isChess960],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMovesGetLegalDestinationsConstMeta =>
      const TaskConstMeta(
        debugName: "get_legal_destinations",
        argNames: ["fen", "square", "isChess960"],
      );

  @override
  Future<Puzzle?> crateApiPuzzlesGetRandomPuzzle({
    required String dbPath,
    int? minRating,
    int? maxRating,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(dbPath, serializer);
          sse_encode_opt_box_autoadd_i_32(minRating, serializer);
          sse_encode_opt_box_autoadd_i_32(maxRating, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_puzzle,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiPuzzlesGetRandomPuzzleConstMeta,
        argValues: [dbPath, minRating, maxRating],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPuzzlesGetRandomPuzzleConstMeta =>
      const TaskConstMeta(
        debugName: "get_random_puzzle",
        argNames: ["dbPath", "minRating", "maxRating"],
      );

  @override
  List<String> crateApiHistoryGetSanHistory({
    required String initialFen,
    required List<String> uciMoves,
    required bool isChess960,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(initialFen, serializer);
          sse_encode_list_String(uciMoves, serializer);
          sse_encode_bool(isChess960, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 16)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiHistoryGetSanHistoryConstMeta,
        argValues: [initialFen, uciMoves, isChess960],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiHistoryGetSanHistoryConstMeta =>
      const TaskConstMeta(
        debugName: "get_san_history",
        argNames: ["initialFen", "uciMoves", "isChess960"],
      );

  @override
  List<String> crateApiThreatsGetThreatenedSquares({
    required String fen,
    required bool isChess960,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(fen, serializer);
          sse_encode_bool(isChess960, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 17)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiThreatsGetThreatenedSquaresConstMeta,
        argValues: [fen, isChess960],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiThreatsGetThreatenedSquaresConstMeta =>
      const TaskConstMeta(
        debugName: "get_threatened_squares",
        argNames: ["fen", "isChess960"],
      );

  @override
  String crateApiSimpleGreet({required String name}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 18)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleGreetConstMeta,
        argValues: [name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGreetConstMeta =>
      const TaskConstMeta(debugName: "greet", argNames: ["name"]);

  @override
  String crateApiHumanizerHumanizeMoveRust({
    required String fenBefore,
    required String moveUci,
    required bool isChess960,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(fenBefore, serializer);
          sse_encode_String(moveUci, serializer);
          sse_encode_bool(isChess960, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 19)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiHumanizerHumanizeMoveRustConstMeta,
        argValues: [fenBefore, moveUci, isChess960],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiHumanizerHumanizeMoveRustConstMeta =>
      const TaskConstMeta(
        debugName: "humanize_move_rust",
        argNames: ["fenBefore", "moveUci", "isChess960"],
      );

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 20,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  List<String> crateApiPgnDbLoadAllGamesFromDb({required String dbPath}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(dbPath, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 21)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiPgnDbLoadAllGamesFromDbConstMeta,
        argValues: [dbPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPgnDbLoadAllGamesFromDbConstMeta =>
      const TaskConstMeta(
        debugName: "load_all_games_from_db",
        argNames: ["dbPath"],
      );

  @override
  List<PgnGameRecord> crateApiPgnDbLoadStudiesFromDb({required String dbPath}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(dbPath, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 22)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_pgn_game_record,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiPgnDbLoadStudiesFromDbConstMeta,
        argValues: [dbPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPgnDbLoadStudiesFromDbConstMeta =>
      const TaskConstMeta(
        debugName: "load_studies_from_db",
        argNames: ["dbPath"],
      );

  @override
  List<PgnGameRecord> crateApiPgnDbParsePgnDatabase({required String pgnText}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(pgnText, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 23)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_pgn_game_record,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiPgnDbParsePgnDatabaseConstMeta,
        argValues: [pgnText],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPgnDbParsePgnDatabaseConstMeta =>
      const TaskConstMeta(
        debugName: "parse_pgn_database",
        argNames: ["pgnText"],
      );

  @override
  ChanakyaRoutine crateApiAssignmentRecommendTasksRust({
    required int elo,
    required ScotomaResult scotoma,
    required List<int> completedTutorials,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_32(elo, serializer);
          sse_encode_box_autoadd_scotoma_result(scotoma, serializer);
          sse_encode_list_prim_i_32_loose(completedTutorials, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 24)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_chanakya_routine,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAssignmentRecommendTasksRustConstMeta,
        argValues: [elo, scotoma, completedTutorials],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAssignmentRecommendTasksRustConstMeta =>
      const TaskConstMeta(
        debugName: "recommend_tasks_rust",
        argNames: ["elo", "scotoma", "completedTutorials"],
      );

  @override
  void crateApiCommentaryResetCommentaryHistoryRust() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 25)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCommentaryResetCommentaryHistoryRustConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCommentaryResetCommentaryHistoryRustConstMeta =>
      const TaskConstMeta(
        debugName: "reset_commentary_history_rust",
        argNames: [],
      );

  @override
  bool crateApiPgnDbSaveGameToDb({
    required String dbPath,
    required String id,
    required String savedAt,
    required String jsonData,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(dbPath, serializer);
          sse_encode_String(id, serializer);
          sse_encode_String(savedAt, serializer);
          sse_encode_String(jsonData, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 26)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiPgnDbSaveGameToDbConstMeta,
        argValues: [dbPath, id, savedAt, jsonData],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPgnDbSaveGameToDbConstMeta => const TaskConstMeta(
    debugName: "save_game_to_db",
    argNames: ["dbPath", "id", "savedAt", "jsonData"],
  );

  @override
  bool crateApiPgnDbSaveStudyToDb({
    required String dbPath,
    required PgnGameRecord game,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(dbPath, serializer);
          sse_encode_box_autoadd_pgn_game_record(game, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 27)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiPgnDbSaveStudyToDbConstMeta,
        argValues: [dbPath, game],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPgnDbSaveStudyToDbConstMeta => const TaskConstMeta(
    debugName: "save_study_to_db",
    argNames: ["dbPath", "game"],
  );

  @override
  Future<List<Puzzle>> crateApiPuzzlesSearchPuzzles({
    required String dbPath,
    String? theme,
    int? minRating,
    int? maxRating,
    int? limit,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(dbPath, serializer);
          sse_encode_opt_String(theme, serializer);
          sse_encode_opt_box_autoadd_i_32(minRating, serializer);
          sse_encode_opt_box_autoadd_i_32(maxRating, serializer);
          sse_encode_opt_box_autoadd_i_32(limit, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 28,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_puzzle,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiPuzzlesSearchPuzzlesConstMeta,
        argValues: [dbPath, theme, minRating, maxRating, limit],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPuzzlesSearchPuzzlesConstMeta =>
      const TaskConstMeta(
        debugName: "search_puzzles",
        argNames: ["dbPath", "theme", "minRating", "maxRating", "limit"],
      );

  @override
  String crateApiChanakyaSelectChanakyaMoveRust({
    required String fen,
    required List<ChanakyaCandidate> candidates,
    required ChanakyaScotoma scotoma,
    required ChanakyaPlaystyle playstyle,
    required int halfMoveCount,
    required double evalAbs,
    required bool isChess960,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(fen, serializer);
          sse_encode_list_chanakya_candidate(candidates, serializer);
          sse_encode_box_autoadd_chanakya_scotoma(scotoma, serializer);
          sse_encode_box_autoadd_chanakya_playstyle(playstyle, serializer);
          sse_encode_i_32(halfMoveCount, serializer);
          sse_encode_f_64(evalAbs, serializer);
          sse_encode_bool(isChess960, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 29)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiChanakyaSelectChanakyaMoveRustConstMeta,
        argValues: [
          fen,
          candidates,
          scotoma,
          playstyle,
          halfMoveCount,
          evalAbs,
          isChess960,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiChanakyaSelectChanakyaMoveRustConstMeta =>
      const TaskConstMeta(
        debugName: "select_chanakya_move_rust",
        argNames: [
          "fen",
          "candidates",
          "scotoma",
          "playstyle",
          "halfMoveCount",
          "evalAbs",
          "isChess960",
        ],
      );

  @override
  String crateApiCommentarySelectCommentaryTemplateRust({
    required String quality,
    required String previousQuality,
    required String gamePhase,
    required double evalDiff,
    required bool hasFork,
    required bool hasPin,
    required bool hasHanging,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(quality, serializer);
          sse_encode_String(previousQuality, serializer);
          sse_encode_String(gamePhase, serializer);
          sse_encode_f_64(evalDiff, serializer);
          sse_encode_bool(hasFork, serializer);
          sse_encode_bool(hasPin, serializer);
          sse_encode_bool(hasHanging, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 30)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCommentarySelectCommentaryTemplateRustConstMeta,
        argValues: [
          quality,
          previousQuality,
          gamePhase,
          evalDiff,
          hasFork,
          hasPin,
          hasHanging,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCommentarySelectCommentaryTemplateRustConstMeta =>
      const TaskConstMeta(
        debugName: "select_commentary_template_rust",
        argNames: [
          "quality",
          "previousQuality",
          "gamePhase",
          "evalDiff",
          "hasFork",
          "hasPin",
          "hasHanging",
        ],
      );

  @override
  String crateApiPersonaSelectPersonaMoveRust({
    required String fen,
    required List<PersonaCandidate> candidates,
    required String avatarName,
    required bool isChess960,
    required int moveCount,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(fen, serializer);
          sse_encode_list_persona_candidate(candidates, serializer);
          sse_encode_String(avatarName, serializer);
          sse_encode_bool(isChess960, serializer);
          sse_encode_i_32(moveCount, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 31)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiPersonaSelectPersonaMoveRustConstMeta,
        argValues: [fen, candidates, avatarName, isChess960, moveCount],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPersonaSelectPersonaMoveRustConstMeta =>
      const TaskConstMeta(
        debugName: "select_persona_move_rust",
        argNames: [
          "fen",
          "candidates",
          "avatarName",
          "isChess960",
          "moveCount",
        ],
      );

  @override
  String? crateApiStateValidateAndApplyMove({
    required String currentFen,
    required String fromStr,
    required String toStr,
    required String promotionStr,
    required bool isChess960,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(currentFen, serializer);
          sse_encode_String(fromStr, serializer);
          sse_encode_String(toStr, serializer);
          sse_encode_String(promotionStr, serializer);
          sse_encode_bool(isChess960, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 32)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiStateValidateAndApplyMoveConstMeta,
        argValues: [currentFen, fromStr, toStr, promotionStr, isChess960],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStateValidateAndApplyMoveConstMeta =>
      const TaskConstMeta(
        debugName: "validate_and_apply_move",
        argNames: [
          "currentFen",
          "fromStr",
          "toStr",
          "promotionStr",
          "isChess960",
        ],
      );

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  ChanakyaPlaystyle dco_decode_box_autoadd_chanakya_playstyle(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_chanakya_playstyle(raw);
  }

  @protected
  ChanakyaScotoma dco_decode_box_autoadd_chanakya_scotoma(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_chanakya_scotoma(raw);
  }

  @protected
  int dco_decode_box_autoadd_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PgnGameHeader dco_decode_box_autoadd_pgn_game_header(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_pgn_game_header(raw);
  }

  @protected
  PgnGameRecord dco_decode_box_autoadd_pgn_game_record(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_pgn_game_record(raw);
  }

  @protected
  Puzzle dco_decode_box_autoadd_puzzle(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_puzzle(raw);
  }

  @protected
  ScotomaResult dco_decode_box_autoadd_scotoma_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_scotoma_result(raw);
  }

  @protected
  ChanakyaCandidate dco_decode_chanakya_candidate(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return ChanakyaCandidate(
      uciMove: dco_decode_String(arr[0]),
      evaluation: dco_decode_f_64(arr[1]),
    );
  }

  @protected
  ChanakyaPlaystyle dco_decode_chanakya_playstyle(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return ChanakyaPlaystyle(
      aggression: dco_decode_f_64(arr[0]),
      intensity: dco_decode_f_64(arr[1]),
      speed: dco_decode_f_64(arr[2]),
    );
  }

  @protected
  ChanakyaRoutine dco_decode_chanakya_routine(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return ChanakyaRoutine(
      tasks: dco_decode_list_chanakya_task(arr[0]),
      wisdomMessage: dco_decode_String(arr[1]),
    );
  }

  @protected
  ChanakyaScotoma dco_decode_chanakya_scotoma(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 8)
      throw Exception('unexpected arr length: expect 8 but see ${arr.length}');
    return ChanakyaScotoma(
      diagonalRetreats: dco_decode_f_64(arr[0]),
      horizontalSwings: dco_decode_f_64(arr[1]),
      knightForks: dco_decode_f_64(arr[2]),
      pinnedPieces: dco_decode_f_64(arr[3]),
      kingSafety: dco_decode_f_64(arr[4]),
      materialGreed: dco_decode_f_64(arr[5]),
      tunnelVision: dco_decode_f_64(arr[6]),
      timePanic: dco_decode_f_64(arr[7]),
    );
  }

  @protected
  ChanakyaTask dco_decode_chanakya_task(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return ChanakyaTask(
      title: dco_decode_String(arr[0]),
      description: dco_decode_String(arr[1]),
      taskType: dco_decode_chanakya_task_type(arr[2]),
      targetId: dco_decode_String(arr[3]),
      targetValue: dco_decode_i_32(arr[4]),
    );
  }

  @protected
  ChanakyaTaskType dco_decode_chanakya_task_type(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ChanakyaTaskType.values[raw as int];
  }

  @protected
  ChanakyaWeeklySummary dco_decode_chanakya_weekly_summary(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return ChanakyaWeeklySummary(
      blundersFound: dco_decode_i_32(arr[0]),
      annotatedMovesCount: dco_decode_i_32(arr[1]),
      worstScotomaAxis: dco_decode_String(arr[2]),
      matchCategory: dco_decode_String(arr[3]),
      commentaryPrompt: dco_decode_String(arr[4]),
      fallbackReport: dco_decode_String(arr[5]),
    );
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  GameIncidents dco_decode_game_incidents(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 8)
      throw Exception('unexpected arr length: expect 8 but see ${arr.length}');
    return GameIncidents(
      diagonalRetreats: dco_decode_bool(arr[0]),
      horizontalSwings: dco_decode_bool(arr[1]),
      knightForks: dco_decode_bool(arr[2]),
      timePanic: dco_decode_bool(arr[3]),
      materialGreed: dco_decode_bool(arr[4]),
      tunnelVision: dco_decode_bool(arr[5]),
      pinnedPieces: dco_decode_bool(arr[6]),
      kingSafety: dco_decode_bool(arr[7]),
    );
  }

  @protected
  GameTerminationStatus dco_decode_game_termination_status(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return GameTerminationStatus(
      isGameOver: dco_decode_bool(arr[0]),
      isCheck: dco_decode_bool(arr[1]),
      isCheckmate: dco_decode_bool(arr[2]),
      isStalemate: dco_decode_bool(arr[3]),
      isInsufficientMaterial: dco_decode_bool(arr[4]),
    );
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<ChanakyaCandidate> dco_decode_list_chanakya_candidate(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_chanakya_candidate).toList();
  }

  @protected
  List<ChanakyaTask> dco_decode_list_chanakya_task(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_chanakya_task).toList();
  }

  @protected
  List<PersonaCandidate> dco_decode_list_persona_candidate(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_persona_candidate).toList();
  }

  @protected
  List<PgnGameRecord> dco_decode_list_pgn_game_record(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_pgn_game_record).toList();
  }

  @protected
  List<int> dco_decode_list_prim_i_32_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Int32List dco_decode_list_prim_i_32_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Int32List;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<Puzzle> dco_decode_list_puzzle(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_puzzle).toList();
  }

  @protected
  List<SavedGameUci> dco_decode_list_saved_game_uci(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_saved_game_uci).toList();
  }

  @protected
  List<StockfishTacticLine> dco_decode_list_stockfish_tactic_line(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_stockfish_tactic_line)
        .toList();
  }

  @protected
  List<TacticData> dco_decode_list_tactic_data(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_tactic_data).toList();
  }

  @protected
  MiddlegameResult dco_decode_middlegame_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return MiddlegameResult(
      mpi: dco_decode_f_64(arr[0]),
      decidedPercentage: dco_decode_f_64(arr[1]),
      winRate: dco_decode_f_64(arr[2]),
      totalMiddlegames: dco_decode_i_32(arr[3]),
    );
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_i_32(raw);
  }

  @protected
  Puzzle? dco_decode_opt_box_autoadd_puzzle(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_puzzle(raw);
  }

  @protected
  PersonaCandidate dco_decode_persona_candidate(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return PersonaCandidate(
      uciMove: dco_decode_String(arr[0]),
      evaluation: dco_decode_f_64(arr[1]),
    );
  }

  @protected
  PgnGameHeader dco_decode_pgn_game_header(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 10)
      throw Exception('unexpected arr length: expect 10 but see ${arr.length}');
    return PgnGameHeader(
      event: dco_decode_String(arr[0]),
      site: dco_decode_String(arr[1]),
      date: dco_decode_String(arr[2]),
      white: dco_decode_String(arr[3]),
      black: dco_decode_String(arr[4]),
      whiteElo: dco_decode_opt_box_autoadd_i_32(arr[5]),
      blackElo: dco_decode_opt_box_autoadd_i_32(arr[6]),
      result: dco_decode_String(arr[7]),
      eco: dco_decode_String(arr[8]),
      opening: dco_decode_String(arr[9]),
    );
  }

  @protected
  PgnGameRecord dco_decode_pgn_game_record(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return PgnGameRecord(
      header: dco_decode_pgn_game_header(arr[0]),
      movesPgn: dco_decode_String(arr[1]),
      index: dco_decode_usize(arr[2]),
    );
  }

  @protected
  PositionMetrics dco_decode_position_metrics(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return PositionMetrics(
      pieceCount: dco_decode_u_32(arr[0]),
      gamePhase: dco_decode_String(arr[1]),
    );
  }

  @protected
  Puzzle dco_decode_puzzle(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return Puzzle(
      id: dco_decode_String(arr[0]),
      fen: dco_decode_String(arr[1]),
      moves: dco_decode_list_String(arr[2]),
      rating: dco_decode_i_32(arr[3]),
      themes: dco_decode_String(arr[4]),
    );
  }

  @protected
  (String, String) dco_decode_record_string_string(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2) {
      throw Exception('Expected 2 elements, got ${arr.length}');
    }
    return (dco_decode_String(arr[0]), dco_decode_String(arr[1]));
  }

  @protected
  SavedGameUci dco_decode_saved_game_uci(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 10)
      throw Exception('unexpected arr length: expect 10 but see ${arr.length}');
    return SavedGameUci(
      recentMoves: dco_decode_list_String(arr[0]),
      uciMoves: dco_decode_list_String(arr[1]),
      initialFen: dco_decode_opt_String(arr[2]),
      finalFen: dco_decode_String(arr[3]),
      isChess960: dco_decode_bool(arr[4]),
      isPlayerWhite: dco_decode_bool(arr[5]),
      result: dco_decode_String(arr[6]),
      whiteTimeLeftMs: dco_decode_i_32(arr[7]),
      blackTimeLeftMs: dco_decode_i_32(arr[8]),
      ratingCategory: dco_decode_String(arr[9]),
    );
  }

  @protected
  ScotomaResult dco_decode_scotoma_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 11)
      throw Exception('unexpected arr length: expect 11 but see ${arr.length}');
    return ScotomaResult(
      diagonalRetreats: dco_decode_f_64(arr[0]),
      horizontalSwings: dco_decode_f_64(arr[1]),
      knightForks: dco_decode_f_64(arr[2]),
      timePanic: dco_decode_f_64(arr[3]),
      materialGreed: dco_decode_f_64(arr[4]),
      tunnelVision: dco_decode_f_64(arr[5]),
      pinnedPieces: dco_decode_f_64(arr[6]),
      kingSafety: dco_decode_f_64(arr[7]),
      totalRatedGames: dco_decode_i_32(arr[8]),
      analyzedGames: dco_decode_i_32(arr[9]),
      skippedGames: dco_decode_i_32(arr[10]),
    );
  }

  @protected
  StockfishTacticLine dco_decode_stockfish_tactic_line(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return StockfishTacticLine(
      moveUci: dco_decode_String(arr[0]),
      evaluation: dco_decode_f_64(arr[1]),
      pv: dco_decode_list_String(arr[2]),
    );
  }

  @protected
  TacticData dco_decode_tactic_data(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return TacticData(
      name: dco_decode_String(arr[0]),
      moves: dco_decode_list_String(arr[1]),
      sanMoves: dco_decode_list_String(arr[2]),
      explanation: dco_decode_String(arr[3]),
    );
  }

  @protected
  TacticsResult dco_decode_tactics_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return TacticsResult(
      textResponse: dco_decode_String(arr[0]),
      yourTactic: dco_decode_tactic_data(arr[1]),
      alternatives: dco_decode_list_tactic_data(arr[2]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  ChanakyaPlaystyle sse_decode_box_autoadd_chanakya_playstyle(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_chanakya_playstyle(deserializer));
  }

  @protected
  ChanakyaScotoma sse_decode_box_autoadd_chanakya_scotoma(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_chanakya_scotoma(deserializer));
  }

  @protected
  int sse_decode_box_autoadd_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_i_32(deserializer));
  }

  @protected
  PgnGameHeader sse_decode_box_autoadd_pgn_game_header(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_pgn_game_header(deserializer));
  }

  @protected
  PgnGameRecord sse_decode_box_autoadd_pgn_game_record(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_pgn_game_record(deserializer));
  }

  @protected
  Puzzle sse_decode_box_autoadd_puzzle(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_puzzle(deserializer));
  }

  @protected
  ScotomaResult sse_decode_box_autoadd_scotoma_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_scotoma_result(deserializer));
  }

  @protected
  ChanakyaCandidate sse_decode_chanakya_candidate(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_uciMove = sse_decode_String(deserializer);
    var var_evaluation = sse_decode_f_64(deserializer);
    return ChanakyaCandidate(uciMove: var_uciMove, evaluation: var_evaluation);
  }

  @protected
  ChanakyaPlaystyle sse_decode_chanakya_playstyle(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_aggression = sse_decode_f_64(deserializer);
    var var_intensity = sse_decode_f_64(deserializer);
    var var_speed = sse_decode_f_64(deserializer);
    return ChanakyaPlaystyle(
      aggression: var_aggression,
      intensity: var_intensity,
      speed: var_speed,
    );
  }

  @protected
  ChanakyaRoutine sse_decode_chanakya_routine(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_tasks = sse_decode_list_chanakya_task(deserializer);
    var var_wisdomMessage = sse_decode_String(deserializer);
    return ChanakyaRoutine(tasks: var_tasks, wisdomMessage: var_wisdomMessage);
  }

  @protected
  ChanakyaScotoma sse_decode_chanakya_scotoma(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_diagonalRetreats = sse_decode_f_64(deserializer);
    var var_horizontalSwings = sse_decode_f_64(deserializer);
    var var_knightForks = sse_decode_f_64(deserializer);
    var var_pinnedPieces = sse_decode_f_64(deserializer);
    var var_kingSafety = sse_decode_f_64(deserializer);
    var var_materialGreed = sse_decode_f_64(deserializer);
    var var_tunnelVision = sse_decode_f_64(deserializer);
    var var_timePanic = sse_decode_f_64(deserializer);
    return ChanakyaScotoma(
      diagonalRetreats: var_diagonalRetreats,
      horizontalSwings: var_horizontalSwings,
      knightForks: var_knightForks,
      pinnedPieces: var_pinnedPieces,
      kingSafety: var_kingSafety,
      materialGreed: var_materialGreed,
      tunnelVision: var_tunnelVision,
      timePanic: var_timePanic,
    );
  }

  @protected
  ChanakyaTask sse_decode_chanakya_task(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_title = sse_decode_String(deserializer);
    var var_description = sse_decode_String(deserializer);
    var var_taskType = sse_decode_chanakya_task_type(deserializer);
    var var_targetId = sse_decode_String(deserializer);
    var var_targetValue = sse_decode_i_32(deserializer);
    return ChanakyaTask(
      title: var_title,
      description: var_description,
      taskType: var_taskType,
      targetId: var_targetId,
      targetValue: var_targetValue,
    );
  }

  @protected
  ChanakyaTaskType sse_decode_chanakya_task_type(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return ChanakyaTaskType.values[inner];
  }

  @protected
  ChanakyaWeeklySummary sse_decode_chanakya_weekly_summary(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_blundersFound = sse_decode_i_32(deserializer);
    var var_annotatedMovesCount = sse_decode_i_32(deserializer);
    var var_worstScotomaAxis = sse_decode_String(deserializer);
    var var_matchCategory = sse_decode_String(deserializer);
    var var_commentaryPrompt = sse_decode_String(deserializer);
    var var_fallbackReport = sse_decode_String(deserializer);
    return ChanakyaWeeklySummary(
      blundersFound: var_blundersFound,
      annotatedMovesCount: var_annotatedMovesCount,
      worstScotomaAxis: var_worstScotomaAxis,
      matchCategory: var_matchCategory,
      commentaryPrompt: var_commentaryPrompt,
      fallbackReport: var_fallbackReport,
    );
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  GameIncidents sse_decode_game_incidents(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_diagonalRetreats = sse_decode_bool(deserializer);
    var var_horizontalSwings = sse_decode_bool(deserializer);
    var var_knightForks = sse_decode_bool(deserializer);
    var var_timePanic = sse_decode_bool(deserializer);
    var var_materialGreed = sse_decode_bool(deserializer);
    var var_tunnelVision = sse_decode_bool(deserializer);
    var var_pinnedPieces = sse_decode_bool(deserializer);
    var var_kingSafety = sse_decode_bool(deserializer);
    return GameIncidents(
      diagonalRetreats: var_diagonalRetreats,
      horizontalSwings: var_horizontalSwings,
      knightForks: var_knightForks,
      timePanic: var_timePanic,
      materialGreed: var_materialGreed,
      tunnelVision: var_tunnelVision,
      pinnedPieces: var_pinnedPieces,
      kingSafety: var_kingSafety,
    );
  }

  @protected
  GameTerminationStatus sse_decode_game_termination_status(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_isGameOver = sse_decode_bool(deserializer);
    var var_isCheck = sse_decode_bool(deserializer);
    var var_isCheckmate = sse_decode_bool(deserializer);
    var var_isStalemate = sse_decode_bool(deserializer);
    var var_isInsufficientMaterial = sse_decode_bool(deserializer);
    return GameTerminationStatus(
      isGameOver: var_isGameOver,
      isCheck: var_isCheck,
      isCheckmate: var_isCheckmate,
      isStalemate: var_isStalemate,
      isInsufficientMaterial: var_isInsufficientMaterial,
    );
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<ChanakyaCandidate> sse_decode_list_chanakya_candidate(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ChanakyaCandidate>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_chanakya_candidate(deserializer));
    }
    return ans_;
  }

  @protected
  List<ChanakyaTask> sse_decode_list_chanakya_task(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ChanakyaTask>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_chanakya_task(deserializer));
    }
    return ans_;
  }

  @protected
  List<PersonaCandidate> sse_decode_list_persona_candidate(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <PersonaCandidate>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_persona_candidate(deserializer));
    }
    return ans_;
  }

  @protected
  List<PgnGameRecord> sse_decode_list_pgn_game_record(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <PgnGameRecord>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_pgn_game_record(deserializer));
    }
    return ans_;
  }

  @protected
  List<int> sse_decode_list_prim_i_32_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getInt32List(len_);
  }

  @protected
  Int32List sse_decode_list_prim_i_32_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getInt32List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<Puzzle> sse_decode_list_puzzle(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Puzzle>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_puzzle(deserializer));
    }
    return ans_;
  }

  @protected
  List<SavedGameUci> sse_decode_list_saved_game_uci(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <SavedGameUci>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_saved_game_uci(deserializer));
    }
    return ans_;
  }

  @protected
  List<StockfishTacticLine> sse_decode_list_stockfish_tactic_line(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <StockfishTacticLine>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_stockfish_tactic_line(deserializer));
    }
    return ans_;
  }

  @protected
  List<TacticData> sse_decode_list_tactic_data(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <TacticData>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_tactic_data(deserializer));
    }
    return ans_;
  }

  @protected
  MiddlegameResult sse_decode_middlegame_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_mpi = sse_decode_f_64(deserializer);
    var var_decidedPercentage = sse_decode_f_64(deserializer);
    var var_winRate = sse_decode_f_64(deserializer);
    var var_totalMiddlegames = sse_decode_i_32(deserializer);
    return MiddlegameResult(
      mpi: var_mpi,
      decidedPercentage: var_decidedPercentage,
      winRate: var_winRate,
      totalMiddlegames: var_totalMiddlegames,
    );
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_i_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  Puzzle? sse_decode_opt_box_autoadd_puzzle(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_puzzle(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PersonaCandidate sse_decode_persona_candidate(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_uciMove = sse_decode_String(deserializer);
    var var_evaluation = sse_decode_f_64(deserializer);
    return PersonaCandidate(uciMove: var_uciMove, evaluation: var_evaluation);
  }

  @protected
  PgnGameHeader sse_decode_pgn_game_header(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_event = sse_decode_String(deserializer);
    var var_site = sse_decode_String(deserializer);
    var var_date = sse_decode_String(deserializer);
    var var_white = sse_decode_String(deserializer);
    var var_black = sse_decode_String(deserializer);
    var var_whiteElo = sse_decode_opt_box_autoadd_i_32(deserializer);
    var var_blackElo = sse_decode_opt_box_autoadd_i_32(deserializer);
    var var_result = sse_decode_String(deserializer);
    var var_eco = sse_decode_String(deserializer);
    var var_opening = sse_decode_String(deserializer);
    return PgnGameHeader(
      event: var_event,
      site: var_site,
      date: var_date,
      white: var_white,
      black: var_black,
      whiteElo: var_whiteElo,
      blackElo: var_blackElo,
      result: var_result,
      eco: var_eco,
      opening: var_opening,
    );
  }

  @protected
  PgnGameRecord sse_decode_pgn_game_record(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_header = sse_decode_pgn_game_header(deserializer);
    var var_movesPgn = sse_decode_String(deserializer);
    var var_index = sse_decode_usize(deserializer);
    return PgnGameRecord(
      header: var_header,
      movesPgn: var_movesPgn,
      index: var_index,
    );
  }

  @protected
  PositionMetrics sse_decode_position_metrics(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_pieceCount = sse_decode_u_32(deserializer);
    var var_gamePhase = sse_decode_String(deserializer);
    return PositionMetrics(
      pieceCount: var_pieceCount,
      gamePhase: var_gamePhase,
    );
  }

  @protected
  Puzzle sse_decode_puzzle(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_fen = sse_decode_String(deserializer);
    var var_moves = sse_decode_list_String(deserializer);
    var var_rating = sse_decode_i_32(deserializer);
    var var_themes = sse_decode_String(deserializer);
    return Puzzle(
      id: var_id,
      fen: var_fen,
      moves: var_moves,
      rating: var_rating,
      themes: var_themes,
    );
  }

  @protected
  (String, String) sse_decode_record_string_string(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_field0 = sse_decode_String(deserializer);
    var var_field1 = sse_decode_String(deserializer);
    return (var_field0, var_field1);
  }

  @protected
  SavedGameUci sse_decode_saved_game_uci(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_recentMoves = sse_decode_list_String(deserializer);
    var var_uciMoves = sse_decode_list_String(deserializer);
    var var_initialFen = sse_decode_opt_String(deserializer);
    var var_finalFen = sse_decode_String(deserializer);
    var var_isChess960 = sse_decode_bool(deserializer);
    var var_isPlayerWhite = sse_decode_bool(deserializer);
    var var_result = sse_decode_String(deserializer);
    var var_whiteTimeLeftMs = sse_decode_i_32(deserializer);
    var var_blackTimeLeftMs = sse_decode_i_32(deserializer);
    var var_ratingCategory = sse_decode_String(deserializer);
    return SavedGameUci(
      recentMoves: var_recentMoves,
      uciMoves: var_uciMoves,
      initialFen: var_initialFen,
      finalFen: var_finalFen,
      isChess960: var_isChess960,
      isPlayerWhite: var_isPlayerWhite,
      result: var_result,
      whiteTimeLeftMs: var_whiteTimeLeftMs,
      blackTimeLeftMs: var_blackTimeLeftMs,
      ratingCategory: var_ratingCategory,
    );
  }

  @protected
  ScotomaResult sse_decode_scotoma_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_diagonalRetreats = sse_decode_f_64(deserializer);
    var var_horizontalSwings = sse_decode_f_64(deserializer);
    var var_knightForks = sse_decode_f_64(deserializer);
    var var_timePanic = sse_decode_f_64(deserializer);
    var var_materialGreed = sse_decode_f_64(deserializer);
    var var_tunnelVision = sse_decode_f_64(deserializer);
    var var_pinnedPieces = sse_decode_f_64(deserializer);
    var var_kingSafety = sse_decode_f_64(deserializer);
    var var_totalRatedGames = sse_decode_i_32(deserializer);
    var var_analyzedGames = sse_decode_i_32(deserializer);
    var var_skippedGames = sse_decode_i_32(deserializer);
    return ScotomaResult(
      diagonalRetreats: var_diagonalRetreats,
      horizontalSwings: var_horizontalSwings,
      knightForks: var_knightForks,
      timePanic: var_timePanic,
      materialGreed: var_materialGreed,
      tunnelVision: var_tunnelVision,
      pinnedPieces: var_pinnedPieces,
      kingSafety: var_kingSafety,
      totalRatedGames: var_totalRatedGames,
      analyzedGames: var_analyzedGames,
      skippedGames: var_skippedGames,
    );
  }

  @protected
  StockfishTacticLine sse_decode_stockfish_tactic_line(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_moveUci = sse_decode_String(deserializer);
    var var_evaluation = sse_decode_f_64(deserializer);
    var var_pv = sse_decode_list_String(deserializer);
    return StockfishTacticLine(
      moveUci: var_moveUci,
      evaluation: var_evaluation,
      pv: var_pv,
    );
  }

  @protected
  TacticData sse_decode_tactic_data(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_moves = sse_decode_list_String(deserializer);
    var var_sanMoves = sse_decode_list_String(deserializer);
    var var_explanation = sse_decode_String(deserializer);
    return TacticData(
      name: var_name,
      moves: var_moves,
      sanMoves: var_sanMoves,
      explanation: var_explanation,
    );
  }

  @protected
  TacticsResult sse_decode_tactics_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_textResponse = sse_decode_String(deserializer);
    var var_yourTactic = sse_decode_tactic_data(deserializer);
    var var_alternatives = sse_decode_list_tactic_data(deserializer);
    return TacticsResult(
      textResponse: var_textResponse,
      yourTactic: var_yourTactic,
      alternatives: var_alternatives,
    );
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_chanakya_playstyle(
    ChanakyaPlaystyle self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_chanakya_playstyle(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_chanakya_scotoma(
    ChanakyaScotoma self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_chanakya_scotoma(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_pgn_game_header(
    PgnGameHeader self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_pgn_game_header(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_pgn_game_record(
    PgnGameRecord self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_pgn_game_record(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_puzzle(Puzzle self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_puzzle(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_scotoma_result(
    ScotomaResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_scotoma_result(self, serializer);
  }

  @protected
  void sse_encode_chanakya_candidate(
    ChanakyaCandidate self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.uciMove, serializer);
    sse_encode_f_64(self.evaluation, serializer);
  }

  @protected
  void sse_encode_chanakya_playstyle(
    ChanakyaPlaystyle self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_64(self.aggression, serializer);
    sse_encode_f_64(self.intensity, serializer);
    sse_encode_f_64(self.speed, serializer);
  }

  @protected
  void sse_encode_chanakya_routine(
    ChanakyaRoutine self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_chanakya_task(self.tasks, serializer);
    sse_encode_String(self.wisdomMessage, serializer);
  }

  @protected
  void sse_encode_chanakya_scotoma(
    ChanakyaScotoma self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_64(self.diagonalRetreats, serializer);
    sse_encode_f_64(self.horizontalSwings, serializer);
    sse_encode_f_64(self.knightForks, serializer);
    sse_encode_f_64(self.pinnedPieces, serializer);
    sse_encode_f_64(self.kingSafety, serializer);
    sse_encode_f_64(self.materialGreed, serializer);
    sse_encode_f_64(self.tunnelVision, serializer);
    sse_encode_f_64(self.timePanic, serializer);
  }

  @protected
  void sse_encode_chanakya_task(ChanakyaTask self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.title, serializer);
    sse_encode_String(self.description, serializer);
    sse_encode_chanakya_task_type(self.taskType, serializer);
    sse_encode_String(self.targetId, serializer);
    sse_encode_i_32(self.targetValue, serializer);
  }

  @protected
  void sse_encode_chanakya_task_type(
    ChanakyaTaskType self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_chanakya_weekly_summary(
    ChanakyaWeeklySummary self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.blundersFound, serializer);
    sse_encode_i_32(self.annotatedMovesCount, serializer);
    sse_encode_String(self.worstScotomaAxis, serializer);
    sse_encode_String(self.matchCategory, serializer);
    sse_encode_String(self.commentaryPrompt, serializer);
    sse_encode_String(self.fallbackReport, serializer);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_game_incidents(GameIncidents self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.diagonalRetreats, serializer);
    sse_encode_bool(self.horizontalSwings, serializer);
    sse_encode_bool(self.knightForks, serializer);
    sse_encode_bool(self.timePanic, serializer);
    sse_encode_bool(self.materialGreed, serializer);
    sse_encode_bool(self.tunnelVision, serializer);
    sse_encode_bool(self.pinnedPieces, serializer);
    sse_encode_bool(self.kingSafety, serializer);
  }

  @protected
  void sse_encode_game_termination_status(
    GameTerminationStatus self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.isGameOver, serializer);
    sse_encode_bool(self.isCheck, serializer);
    sse_encode_bool(self.isCheckmate, serializer);
    sse_encode_bool(self.isStalemate, serializer);
    sse_encode_bool(self.isInsufficientMaterial, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_chanakya_candidate(
    List<ChanakyaCandidate> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_chanakya_candidate(item, serializer);
    }
  }

  @protected
  void sse_encode_list_chanakya_task(
    List<ChanakyaTask> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_chanakya_task(item, serializer);
    }
  }

  @protected
  void sse_encode_list_persona_candidate(
    List<PersonaCandidate> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_persona_candidate(item, serializer);
    }
  }

  @protected
  void sse_encode_list_pgn_game_record(
    List<PgnGameRecord> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_pgn_game_record(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_i_32_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putInt32List(
      self is Int32List ? self : Int32List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_i_32_strict(
    Int32List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putInt32List(self);
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_puzzle(List<Puzzle> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_puzzle(item, serializer);
    }
  }

  @protected
  void sse_encode_list_saved_game_uci(
    List<SavedGameUci> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_saved_game_uci(item, serializer);
    }
  }

  @protected
  void sse_encode_list_stockfish_tactic_line(
    List<StockfishTacticLine> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_stockfish_tactic_line(item, serializer);
    }
  }

  @protected
  void sse_encode_list_tactic_data(
    List<TacticData> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_tactic_data(item, serializer);
    }
  }

  @protected
  void sse_encode_middlegame_result(
    MiddlegameResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_64(self.mpi, serializer);
    sse_encode_f_64(self.decidedPercentage, serializer);
    sse_encode_f_64(self.winRate, serializer);
    sse_encode_i_32(self.totalMiddlegames, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_i_32(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_i_32(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_puzzle(
    Puzzle? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_puzzle(self, serializer);
    }
  }

  @protected
  void sse_encode_persona_candidate(
    PersonaCandidate self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.uciMove, serializer);
    sse_encode_f_64(self.evaluation, serializer);
  }

  @protected
  void sse_encode_pgn_game_header(
    PgnGameHeader self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.event, serializer);
    sse_encode_String(self.site, serializer);
    sse_encode_String(self.date, serializer);
    sse_encode_String(self.white, serializer);
    sse_encode_String(self.black, serializer);
    sse_encode_opt_box_autoadd_i_32(self.whiteElo, serializer);
    sse_encode_opt_box_autoadd_i_32(self.blackElo, serializer);
    sse_encode_String(self.result, serializer);
    sse_encode_String(self.eco, serializer);
    sse_encode_String(self.opening, serializer);
  }

  @protected
  void sse_encode_pgn_game_record(
    PgnGameRecord self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_pgn_game_header(self.header, serializer);
    sse_encode_String(self.movesPgn, serializer);
    sse_encode_usize(self.index, serializer);
  }

  @protected
  void sse_encode_position_metrics(
    PositionMetrics self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.pieceCount, serializer);
    sse_encode_String(self.gamePhase, serializer);
  }

  @protected
  void sse_encode_puzzle(Puzzle self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.fen, serializer);
    sse_encode_list_String(self.moves, serializer);
    sse_encode_i_32(self.rating, serializer);
    sse_encode_String(self.themes, serializer);
  }

  @protected
  void sse_encode_record_string_string(
    (String, String) self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.$1, serializer);
    sse_encode_String(self.$2, serializer);
  }

  @protected
  void sse_encode_saved_game_uci(SavedGameUci self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_String(self.recentMoves, serializer);
    sse_encode_list_String(self.uciMoves, serializer);
    sse_encode_opt_String(self.initialFen, serializer);
    sse_encode_String(self.finalFen, serializer);
    sse_encode_bool(self.isChess960, serializer);
    sse_encode_bool(self.isPlayerWhite, serializer);
    sse_encode_String(self.result, serializer);
    sse_encode_i_32(self.whiteTimeLeftMs, serializer);
    sse_encode_i_32(self.blackTimeLeftMs, serializer);
    sse_encode_String(self.ratingCategory, serializer);
  }

  @protected
  void sse_encode_scotoma_result(ScotomaResult self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_64(self.diagonalRetreats, serializer);
    sse_encode_f_64(self.horizontalSwings, serializer);
    sse_encode_f_64(self.knightForks, serializer);
    sse_encode_f_64(self.timePanic, serializer);
    sse_encode_f_64(self.materialGreed, serializer);
    sse_encode_f_64(self.tunnelVision, serializer);
    sse_encode_f_64(self.pinnedPieces, serializer);
    sse_encode_f_64(self.kingSafety, serializer);
    sse_encode_i_32(self.totalRatedGames, serializer);
    sse_encode_i_32(self.analyzedGames, serializer);
    sse_encode_i_32(self.skippedGames, serializer);
  }

  @protected
  void sse_encode_stockfish_tactic_line(
    StockfishTacticLine self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.moveUci, serializer);
    sse_encode_f_64(self.evaluation, serializer);
    sse_encode_list_String(self.pv, serializer);
  }

  @protected
  void sse_encode_tactic_data(TacticData self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_list_String(self.moves, serializer);
    sse_encode_list_String(self.sanMoves, serializer);
    sse_encode_String(self.explanation, serializer);
  }

  @protected
  void sse_encode_tactics_result(TacticsResult self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.textResponse, serializer);
    sse_encode_tactic_data(self.yourTactic, serializer);
    sse_encode_list_tactic_data(self.alternatives, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }
}
