// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/chanakya.dart';
import 'api/cognitive.dart';
import 'api/context.dart';
import 'api/history.dart';
import 'api/humanizer.dart';
import 'api/moves.dart';
import 'api/persona.dart';
import 'api/puzzles.dart';
import 'api/simple.dart';
import 'api/state.dart';
import 'api/status.dart';
import 'api/threats.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  ChanakyaPlaystyle dco_decode_box_autoadd_chanakya_playstyle(dynamic raw);

  @protected
  ChanakyaScotoma dco_decode_box_autoadd_chanakya_scotoma(dynamic raw);

  @protected
  int dco_decode_box_autoadd_i_32(dynamic raw);

  @protected
  Puzzle dco_decode_box_autoadd_puzzle(dynamic raw);

  @protected
  ChanakyaCandidate dco_decode_chanakya_candidate(dynamic raw);

  @protected
  ChanakyaPlaystyle dco_decode_chanakya_playstyle(dynamic raw);

  @protected
  ChanakyaScotoma dco_decode_chanakya_scotoma(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  GameTerminationStatus dco_decode_game_termination_status(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<ChanakyaCandidate> dco_decode_list_chanakya_candidate(dynamic raw);

  @protected
  List<PersonaCandidate> dco_decode_list_persona_candidate(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<Puzzle> dco_decode_list_puzzle(dynamic raw);

  @protected
  List<SavedGameUci> dco_decode_list_saved_game_uci(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_i_32(dynamic raw);

  @protected
  Puzzle? dco_decode_opt_box_autoadd_puzzle(dynamic raw);

  @protected
  PersonaCandidate dco_decode_persona_candidate(dynamic raw);

  @protected
  PositionMetrics dco_decode_position_metrics(dynamic raw);

  @protected
  Puzzle dco_decode_puzzle(dynamic raw);

  @protected
  SavedGameUci dco_decode_saved_game_uci(dynamic raw);

  @protected
  ScotomaResult dco_decode_scotoma_result(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  ChanakyaPlaystyle sse_decode_box_autoadd_chanakya_playstyle(
    SseDeserializer deserializer,
  );

  @protected
  ChanakyaScotoma sse_decode_box_autoadd_chanakya_scotoma(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_box_autoadd_i_32(SseDeserializer deserializer);

  @protected
  Puzzle sse_decode_box_autoadd_puzzle(SseDeserializer deserializer);

  @protected
  ChanakyaCandidate sse_decode_chanakya_candidate(SseDeserializer deserializer);

  @protected
  ChanakyaPlaystyle sse_decode_chanakya_playstyle(SseDeserializer deserializer);

  @protected
  ChanakyaScotoma sse_decode_chanakya_scotoma(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  GameTerminationStatus sse_decode_game_termination_status(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<ChanakyaCandidate> sse_decode_list_chanakya_candidate(
    SseDeserializer deserializer,
  );

  @protected
  List<PersonaCandidate> sse_decode_list_persona_candidate(
    SseDeserializer deserializer,
  );

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<Puzzle> sse_decode_list_puzzle(SseDeserializer deserializer);

  @protected
  List<SavedGameUci> sse_decode_list_saved_game_uci(
    SseDeserializer deserializer,
  );

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_i_32(SseDeserializer deserializer);

  @protected
  Puzzle? sse_decode_opt_box_autoadd_puzzle(SseDeserializer deserializer);

  @protected
  PersonaCandidate sse_decode_persona_candidate(SseDeserializer deserializer);

  @protected
  PositionMetrics sse_decode_position_metrics(SseDeserializer deserializer);

  @protected
  Puzzle sse_decode_puzzle(SseDeserializer deserializer);

  @protected
  SavedGameUci sse_decode_saved_game_uci(SseDeserializer deserializer);

  @protected
  ScotomaResult sse_decode_scotoma_result(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_chanakya_playstyle(
    ChanakyaPlaystyle self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_chanakya_scotoma(
    ChanakyaScotoma self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_puzzle(Puzzle self, SseSerializer serializer);

  @protected
  void sse_encode_chanakya_candidate(
    ChanakyaCandidate self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_chanakya_playstyle(
    ChanakyaPlaystyle self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_chanakya_scotoma(
    ChanakyaScotoma self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_game_termination_status(
    GameTerminationStatus self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_chanakya_candidate(
    List<ChanakyaCandidate> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_persona_candidate(
    List<PersonaCandidate> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_puzzle(List<Puzzle> self, SseSerializer serializer);

  @protected
  void sse_encode_list_saved_game_uci(
    List<SavedGameUci> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_i_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_puzzle(
    Puzzle? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_persona_candidate(
    PersonaCandidate self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_position_metrics(
    PositionMetrics self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_puzzle(Puzzle self, SseSerializer serializer);

  @protected
  void sse_encode_saved_game_uci(SavedGameUci self, SseSerializer serializer);

  @protected
  void sse_encode_scotoma_result(ScotomaResult self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
