// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/context.dart';
import 'api/history.dart';
import 'api/moves.dart';
import 'api/puzzles.dart';
import 'api/simple.dart';
import 'api/state.dart';
import 'api/status.dart';
import 'api/threats.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => 750610055;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_kingslayer_chess',
        ioDirectory: 'rust_core/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  GameTerminationStatus crateApiStatusEvaluateGameStatus({
    required String fen,
    required bool isChess960,
  });

  PositionMetrics crateApiContextEvaluatePositionMetrics({
    required String fen,
    required int historyLength,
  });

  List<String> crateApiMovesGetLegalDestinations({
    required String fen,
    required String square,
    required bool isChess960,
  });

  Future<Puzzle?> crateApiPuzzlesGetRandomPuzzle({
    required String dbPath,
    int? minRating,
    int? maxRating,
  });

  List<String> crateApiHistoryGetSanHistory({
    required String initialFen,
    required List<String> uciMoves,
    required bool isChess960,
  });

  List<String> crateApiThreatsGetThreatenedSquares({required String fen});

  String crateApiSimpleGreet({required String name});

  Future<void> crateApiSimpleInitApp();

  Future<List<Puzzle>> crateApiPuzzlesSearchPuzzles({
    required String dbPath,
    String? theme,
    int? minRating,
    int? maxRating,
    int? limit,
  });

  String? crateApiStateValidateAndApplyMove({
    required String currentFen,
    required String fromStr,
    required String toStr,
    required String promotionStr,
    required bool isChess960,
  });
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  GameTerminationStatus crateApiStatusEvaluateGameStatus({
    required String fen,
    required bool isChess960,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(fen, serializer);
          sse_encode_bool(isChess960, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_game_termination_status,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiStatusEvaluateGameStatusConstMeta,
        argValues: [fen, isChess960],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStatusEvaluateGameStatusConstMeta =>
      const TaskConstMeta(
        debugName: "evaluate_game_status",
        argNames: ["fen", "isChess960"],
      );

  @override
  PositionMetrics crateApiContextEvaluatePositionMetrics({
    required String fen,
    required int historyLength,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(fen, serializer);
          sse_encode_u_32(historyLength, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_position_metrics,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiContextEvaluatePositionMetricsConstMeta,
        argValues: [fen, historyLength],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiContextEvaluatePositionMetricsConstMeta =>
      const TaskConstMeta(
        debugName: "evaluate_position_metrics",
        argNames: ["fen", "historyLength"],
      );

  @override
  List<String> crateApiMovesGetLegalDestinations({
    required String fen,
    required String square,
    required bool isChess960,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(fen, serializer);
          sse_encode_String(square, serializer);
          sse_encode_bool(isChess960, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiMovesGetLegalDestinationsConstMeta,
        argValues: [fen, square, isChess960],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMovesGetLegalDestinationsConstMeta =>
      const TaskConstMeta(
        debugName: "get_legal_destinations",
        argNames: ["fen", "square", "isChess960"],
      );

  @override
  Future<Puzzle?> crateApiPuzzlesGetRandomPuzzle({
    required String dbPath,
    int? minRating,
    int? maxRating,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(dbPath, serializer);
          sse_encode_opt_box_autoadd_i_32(minRating, serializer);
          sse_encode_opt_box_autoadd_i_32(maxRating, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_puzzle,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiPuzzlesGetRandomPuzzleConstMeta,
        argValues: [dbPath, minRating, maxRating],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPuzzlesGetRandomPuzzleConstMeta =>
      const TaskConstMeta(
        debugName: "get_random_puzzle",
        argNames: ["dbPath", "minRating", "maxRating"],
      );

  @override
  List<String> crateApiHistoryGetSanHistory({
    required String initialFen,
    required List<String> uciMoves,
    required bool isChess960,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(initialFen, serializer);
          sse_encode_list_String(uciMoves, serializer);
          sse_encode_bool(isChess960, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiHistoryGetSanHistoryConstMeta,
        argValues: [initialFen, uciMoves, isChess960],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiHistoryGetSanHistoryConstMeta =>
      const TaskConstMeta(
        debugName: "get_san_history",
        argNames: ["initialFen", "uciMoves", "isChess960"],
      );

  @override
  List<String> crateApiThreatsGetThreatenedSquares({required String fen}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(fen, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 6)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiThreatsGetThreatenedSquaresConstMeta,
        argValues: [fen],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiThreatsGetThreatenedSquaresConstMeta =>
      const TaskConstMeta(
        debugName: "get_threatened_squares",
        argNames: ["fen"],
      );

  @override
  String crateApiSimpleGreet({required String name}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleGreetConstMeta,
        argValues: [name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGreetConstMeta =>
      const TaskConstMeta(debugName: "greet", argNames: ["name"]);

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<List<Puzzle>> crateApiPuzzlesSearchPuzzles({
    required String dbPath,
    String? theme,
    int? minRating,
    int? maxRating,
    int? limit,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(dbPath, serializer);
          sse_encode_opt_String(theme, serializer);
          sse_encode_opt_box_autoadd_i_32(minRating, serializer);
          sse_encode_opt_box_autoadd_i_32(maxRating, serializer);
          sse_encode_opt_box_autoadd_i_32(limit, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_puzzle,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiPuzzlesSearchPuzzlesConstMeta,
        argValues: [dbPath, theme, minRating, maxRating, limit],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPuzzlesSearchPuzzlesConstMeta =>
      const TaskConstMeta(
        debugName: "search_puzzles",
        argNames: ["dbPath", "theme", "minRating", "maxRating", "limit"],
      );

  @override
  String? crateApiStateValidateAndApplyMove({
    required String currentFen,
    required String fromStr,
    required String toStr,
    required String promotionStr,
    required bool isChess960,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(currentFen, serializer);
          sse_encode_String(fromStr, serializer);
          sse_encode_String(toStr, serializer);
          sse_encode_String(promotionStr, serializer);
          sse_encode_bool(isChess960, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 10)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiStateValidateAndApplyMoveConstMeta,
        argValues: [currentFen, fromStr, toStr, promotionStr, isChess960],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStateValidateAndApplyMoveConstMeta =>
      const TaskConstMeta(
        debugName: "validate_and_apply_move",
        argNames: [
          "currentFen",
          "fromStr",
          "toStr",
          "promotionStr",
          "isChess960",
        ],
      );

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  int dco_decode_box_autoadd_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  Puzzle dco_decode_box_autoadd_puzzle(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_puzzle(raw);
  }

  @protected
  GameTerminationStatus dco_decode_game_termination_status(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return GameTerminationStatus(
      isGameOver: dco_decode_bool(arr[0]),
      isCheck: dco_decode_bool(arr[1]),
      isCheckmate: dco_decode_bool(arr[2]),
      isStalemate: dco_decode_bool(arr[3]),
      isInsufficientMaterial: dco_decode_bool(arr[4]),
    );
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<Puzzle> dco_decode_list_puzzle(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_puzzle).toList();
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_i_32(raw);
  }

  @protected
  Puzzle? dco_decode_opt_box_autoadd_puzzle(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_puzzle(raw);
  }

  @protected
  PositionMetrics dco_decode_position_metrics(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return PositionMetrics(
      pieceCount: dco_decode_u_32(arr[0]),
      gamePhase: dco_decode_String(arr[1]),
    );
  }

  @protected
  Puzzle dco_decode_puzzle(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return Puzzle(
      id: dco_decode_String(arr[0]),
      fen: dco_decode_String(arr[1]),
      moves: dco_decode_list_String(arr[2]),
      rating: dco_decode_i_32(arr[3]),
      themes: dco_decode_String(arr[4]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  int sse_decode_box_autoadd_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_i_32(deserializer));
  }

  @protected
  Puzzle sse_decode_box_autoadd_puzzle(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_puzzle(deserializer));
  }

  @protected
  GameTerminationStatus sse_decode_game_termination_status(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_isGameOver = sse_decode_bool(deserializer);
    var var_isCheck = sse_decode_bool(deserializer);
    var var_isCheckmate = sse_decode_bool(deserializer);
    var var_isStalemate = sse_decode_bool(deserializer);
    var var_isInsufficientMaterial = sse_decode_bool(deserializer);
    return GameTerminationStatus(
      isGameOver: var_isGameOver,
      isCheck: var_isCheck,
      isCheckmate: var_isCheckmate,
      isStalemate: var_isStalemate,
      isInsufficientMaterial: var_isInsufficientMaterial,
    );
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<Puzzle> sse_decode_list_puzzle(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Puzzle>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_puzzle(deserializer));
    }
    return ans_;
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_i_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  Puzzle? sse_decode_opt_box_autoadd_puzzle(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_puzzle(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PositionMetrics sse_decode_position_metrics(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_pieceCount = sse_decode_u_32(deserializer);
    var var_gamePhase = sse_decode_String(deserializer);
    return PositionMetrics(
      pieceCount: var_pieceCount,
      gamePhase: var_gamePhase,
    );
  }

  @protected
  Puzzle sse_decode_puzzle(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_fen = sse_decode_String(deserializer);
    var var_moves = sse_decode_list_String(deserializer);
    var var_rating = sse_decode_i_32(deserializer);
    var var_themes = sse_decode_String(deserializer);
    return Puzzle(
      id: var_id,
      fen: var_fen,
      moves: var_moves,
      rating: var_rating,
      themes: var_themes,
    );
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_puzzle(Puzzle self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_puzzle(self, serializer);
  }

  @protected
  void sse_encode_game_termination_status(
    GameTerminationStatus self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.isGameOver, serializer);
    sse_encode_bool(self.isCheck, serializer);
    sse_encode_bool(self.isCheckmate, serializer);
    sse_encode_bool(self.isStalemate, serializer);
    sse_encode_bool(self.isInsufficientMaterial, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_puzzle(List<Puzzle> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_puzzle(item, serializer);
    }
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_i_32(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_i_32(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_puzzle(
    Puzzle? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_puzzle(self, serializer);
    }
  }

  @protected
  void sse_encode_position_metrics(
    PositionMetrics self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.pieceCount, serializer);
    sse_encode_String(self.gamePhase, serializer);
  }

  @protected
  void sse_encode_puzzle(Puzzle self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.fen, serializer);
    sse_encode_list_String(self.moves, serializer);
    sse_encode_i_32(self.rating, serializer);
    sse_encode_String(self.themes, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }
}
