// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'cognitive.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `get_chanakya_wisdom`, `get_chapter_title`, `get_worst_scotoma`, `select_ai_avatar`, `select_tutorial_target`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`

ChanakyaRoutine recommendTasksRust({
  required int elo,
  required ScotomaResult scotoma,
  required List<int> completedTutorials,
}) => RustLib.instance.api.crateApiAssignmentRecommendTasksRust(
  elo: elo,
  scotoma: scotoma,
  completedTutorials: completedTutorials,
);

ChanakyaWeeklySummary analyzeSubmittedGameRust({
  required String pgnContent,
  required ScotomaResult scotoma,
}) => RustLib.instance.api.crateApiAssignmentAnalyzeSubmittedGameRust(
  pgnContent: pgnContent,
  scotoma: scotoma,
);

class ChanakyaRoutine {
  final List<ChanakyaTask> tasks;
  final String wisdomMessage;

  const ChanakyaRoutine({required this.tasks, required this.wisdomMessage});

  @override
  int get hashCode => tasks.hashCode ^ wisdomMessage.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChanakyaRoutine &&
          runtimeType == other.runtimeType &&
          tasks == other.tasks &&
          wisdomMessage == other.wisdomMessage;
}

class ChanakyaTask {
  final String title;
  final String description;
  final ChanakyaTaskType taskType;
  final String targetId;
  final int targetValue;

  const ChanakyaTask({
    required this.title,
    required this.description,
    required this.taskType,
    required this.targetId,
    required this.targetValue,
  });

  @override
  int get hashCode =>
      title.hashCode ^
      description.hashCode ^
      taskType.hashCode ^
      targetId.hashCode ^
      targetValue.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChanakyaTask &&
          runtimeType == other.runtimeType &&
          title == other.title &&
          description == other.description &&
          taskType == other.taskType &&
          targetId == other.targetId &&
          targetValue == other.targetValue;
}

enum ChanakyaTaskType { arena, puzzle, tutorial }

class ChanakyaWeeklySummary {
  final int blundersFound;
  final int annotatedMovesCount;
  final String worstScotomaAxis;
  final String matchCategory;
  final String commentaryPrompt;
  final String fallbackReport;

  const ChanakyaWeeklySummary({
    required this.blundersFound,
    required this.annotatedMovesCount,
    required this.worstScotomaAxis,
    required this.matchCategory,
    required this.commentaryPrompt,
    required this.fallbackReport,
  });

  @override
  int get hashCode =>
      blundersFound.hashCode ^
      annotatedMovesCount.hashCode ^
      worstScotomaAxis.hashCode ^
      matchCategory.hashCode ^
      commentaryPrompt.hashCode ^
      fallbackReport.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChanakyaWeeklySummary &&
          runtimeType == other.runtimeType &&
          blundersFound == other.blundersFound &&
          annotatedMovesCount == other.annotatedMovesCount &&
          worstScotomaAxis == other.worstScotomaAxis &&
          matchCategory == other.matchCategory &&
          commentaryPrompt == other.commentaryPrompt &&
          fallbackReport == other.fallbackReport;
}
