// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `counts_valuable_attacks_after`, `fen_move_jitter`, `find_legal_move`, `is_diagonal_retreat`, `is_horizontal_swing`, `is_open_file`, `mobility_restriction_delta`, `parse_pos`, `targets_pinned_opponent_piece`, `would_expose_king_to_our_piece`, `would_expose_king`

/// Select the best move for GM Chanakya in Academy Mode.
///
/// The function applies a layered weighting system on top of Stockfish's
/// MultiPV candidates:
///
/// **Layer 1 — Elo-gap variety** (opening jitter, decays after move 12)
///   Adds small random variance so GM Chanakya doesn't always play the most
///   "expected" line when his skill level is much higher than the user.
///
/// **Layer 2 — Tight-Fight precision** (no jitter when game is close)
///   When `eval_abs ≤ 1.5` and `half_move_count ≥ 20`, Chanakya drops all
///   jitter and plays with full Stockfish precision.
///
/// **Layer 3 — Cognitive Scotoma targeting**
///   Each candidate move is scored against the user's known blindspots via
///   sandboxed shakmaty analysis. Moves that exploit blindspots get bonus weight
///   proportional to the blindspot severity (0.0–1.0).
///
/// **Layer 4 — Playstyle countering**
///   If user is an aggressor (aggression > 0.6), Chanakya biases toward
///   defensive, mobility-restricting moves.
///   If user is a passifier (aggression < 0.4), Chanakya biases toward open,
///   attacking, check-giving moves.
String selectChanakyaMoveRust({
  required String fen,
  required List<ChanakyaCandidate> candidates,
  required ChanakyaScotoma scotoma,
  required ChanakyaPlaystyle playstyle,
  required int halfMoveCount,
  required double evalAbs,
  required bool isChess960,
}) => RustLib.instance.api.crateApiChanakyaSelectChanakyaMoveRust(
  fen: fen,
  candidates: candidates,
  scotoma: scotoma,
  playstyle: playstyle,
  halfMoveCount: halfMoveCount,
  evalAbs: evalAbs,
  isChess960: isChess960,
);

/// A single candidate move emitted by Stockfish (MultiPV line).
class ChanakyaCandidate {
  final String uciMove;
  final double evaluation;

  const ChanakyaCandidate({required this.uciMove, required this.evaluation});

  @override
  int get hashCode => uciMove.hashCode ^ evaluation.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChanakyaCandidate &&
          runtimeType == other.runtimeType &&
          uciMove == other.uciMove &&
          evaluation == other.evaluation;
}

/// User playstyle statistics from the radar chart.
class ChanakyaPlaystyle {
  final double aggression;
  final double intensity;
  final double speed;

  const ChanakyaPlaystyle({
    required this.aggression,
    required this.intensity,
    required this.speed,
  });

  @override
  int get hashCode => aggression.hashCode ^ intensity.hashCode ^ speed.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChanakyaPlaystyle &&
          runtimeType == other.runtimeType &&
          aggression == other.aggression &&
          intensity == other.intensity &&
          speed == other.speed;
}

/// User cognitive blindspot profile, populated by `analyze_scotoma`.
class ChanakyaScotoma {
  final double diagonalRetreats;
  final double horizontalSwings;
  final double knightForks;
  final double pinnedPieces;
  final double kingSafety;
  final double materialGreed;
  final double tunnelVision;
  final double timePanic;

  const ChanakyaScotoma({
    required this.diagonalRetreats,
    required this.horizontalSwings,
    required this.knightForks,
    required this.pinnedPieces,
    required this.kingSafety,
    required this.materialGreed,
    required this.tunnelVision,
    required this.timePanic,
  });

  @override
  int get hashCode =>
      diagonalRetreats.hashCode ^
      horizontalSwings.hashCode ^
      knightForks.hashCode ^
      pinnedPieces.hashCode ^
      kingSafety.hashCode ^
      materialGreed.hashCode ^
      tunnelVision.hashCode ^
      timePanic.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChanakyaScotoma &&
          runtimeType == other.runtimeType &&
          diagonalRetreats == other.diagonalRetreats &&
          horizontalSwings == other.horizontalSwings &&
          knightForks == other.knightForks &&
          pinnedPieces == other.pinnedPieces &&
          kingSafety == other.kingSafety &&
          materialGreed == other.materialGreed &&
          tunnelVision == other.tunnelVision &&
          timePanic == other.timePanic;
}
