// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `analyze_game`, `chess960_initial_fens`, `expand_fen_rank`, `fen_position_signature`, `find_uci_move`, `is_endgame`, `is_pinned`, `normalize_chess960_castling_rights`, `parse_position`, `position_signature`, `recover_chess960_initial_fen`, `replay_game`, `replay_san`, `replay_uci`, `rook_file_for_castling`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `ReplayedGame`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`

ScotomaResult analyzeScotoma({required List<SavedGameUci> games}) =>
    RustLib.instance.api.crateApiCognitiveAnalyzeScotoma(games: games);

MiddlegameResult analyzeMiddlegame({
  required List<SavedGameUci> games,
  required ScotomaResult scotoma,
}) => RustLib.instance.api.crateApiCognitiveAnalyzeMiddlegame(
  games: games,
  scotoma: scotoma,
);

class GameIncidents {
  final bool diagonalRetreats;
  final bool horizontalSwings;
  final bool knightForks;
  final bool timePanic;
  final bool materialGreed;
  final bool tunnelVision;
  final bool pinnedPieces;
  final bool kingSafety;

  const GameIncidents({
    required this.diagonalRetreats,
    required this.horizontalSwings,
    required this.knightForks,
    required this.timePanic,
    required this.materialGreed,
    required this.tunnelVision,
    required this.pinnedPieces,
    required this.kingSafety,
  });

  static Future<GameIncidents> default_() =>
      RustLib.instance.api.crateApiCognitiveGameIncidentsDefault();

  @override
  int get hashCode =>
      diagonalRetreats.hashCode ^
      horizontalSwings.hashCode ^
      knightForks.hashCode ^
      timePanic.hashCode ^
      materialGreed.hashCode ^
      tunnelVision.hashCode ^
      pinnedPieces.hashCode ^
      kingSafety.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GameIncidents &&
          runtimeType == other.runtimeType &&
          diagonalRetreats == other.diagonalRetreats &&
          horizontalSwings == other.horizontalSwings &&
          knightForks == other.knightForks &&
          timePanic == other.timePanic &&
          materialGreed == other.materialGreed &&
          tunnelVision == other.tunnelVision &&
          pinnedPieces == other.pinnedPieces &&
          kingSafety == other.kingSafety;
}

class MiddlegameResult {
  final double mpi;
  final double decidedPercentage;
  final double winRate;
  final int totalMiddlegames;

  const MiddlegameResult({
    required this.mpi,
    required this.decidedPercentage,
    required this.winRate,
    required this.totalMiddlegames,
  });

  @override
  int get hashCode =>
      mpi.hashCode ^
      decidedPercentage.hashCode ^
      winRate.hashCode ^
      totalMiddlegames.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MiddlegameResult &&
          runtimeType == other.runtimeType &&
          mpi == other.mpi &&
          decidedPercentage == other.decidedPercentage &&
          winRate == other.winRate &&
          totalMiddlegames == other.totalMiddlegames;
}

class SavedGameUci {
  final List<String> recentMoves;
  final List<String> uciMoves;
  final String? initialFen;
  final String finalFen;
  final bool isChess960;
  final bool isPlayerWhite;
  final String result;
  final int whiteTimeLeftMs;
  final int blackTimeLeftMs;
  final String ratingCategory;

  const SavedGameUci({
    required this.recentMoves,
    required this.uciMoves,
    this.initialFen,
    required this.finalFen,
    required this.isChess960,
    required this.isPlayerWhite,
    required this.result,
    required this.whiteTimeLeftMs,
    required this.blackTimeLeftMs,
    required this.ratingCategory,
  });

  @override
  int get hashCode =>
      recentMoves.hashCode ^
      uciMoves.hashCode ^
      initialFen.hashCode ^
      finalFen.hashCode ^
      isChess960.hashCode ^
      isPlayerWhite.hashCode ^
      result.hashCode ^
      whiteTimeLeftMs.hashCode ^
      blackTimeLeftMs.hashCode ^
      ratingCategory.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SavedGameUci &&
          runtimeType == other.runtimeType &&
          recentMoves == other.recentMoves &&
          uciMoves == other.uciMoves &&
          initialFen == other.initialFen &&
          finalFen == other.finalFen &&
          isChess960 == other.isChess960 &&
          isPlayerWhite == other.isPlayerWhite &&
          result == other.result &&
          whiteTimeLeftMs == other.whiteTimeLeftMs &&
          blackTimeLeftMs == other.blackTimeLeftMs &&
          ratingCategory == other.ratingCategory;
}

class ScotomaResult {
  final double diagonalRetreats;
  final double horizontalSwings;
  final double knightForks;
  final double timePanic;
  final double materialGreed;
  final double tunnelVision;
  final double pinnedPieces;
  final double kingSafety;
  final int totalRatedGames;
  final int analyzedGames;
  final int skippedGames;

  const ScotomaResult({
    required this.diagonalRetreats,
    required this.horizontalSwings,
    required this.knightForks,
    required this.timePanic,
    required this.materialGreed,
    required this.tunnelVision,
    required this.pinnedPieces,
    required this.kingSafety,
    required this.totalRatedGames,
    required this.analyzedGames,
    required this.skippedGames,
  });

  @override
  int get hashCode =>
      diagonalRetreats.hashCode ^
      horizontalSwings.hashCode ^
      knightForks.hashCode ^
      timePanic.hashCode ^
      materialGreed.hashCode ^
      tunnelVision.hashCode ^
      pinnedPieces.hashCode ^
      kingSafety.hashCode ^
      totalRatedGames.hashCode ^
      analyzedGames.hashCode ^
      skippedGames.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ScotomaResult &&
          runtimeType == other.runtimeType &&
          diagonalRetreats == other.diagonalRetreats &&
          horizontalSwings == other.horizontalSwings &&
          knightForks == other.knightForks &&
          timePanic == other.timePanic &&
          materialGreed == other.materialGreed &&
          tunnelVision == other.tunnelVision &&
          pinnedPieces == other.pinnedPieces &&
          kingSafety == other.kingSafety &&
          totalRatedGames == other.totalRatedGames &&
          analyzedGames == other.analyzedGames &&
          skippedGames == other.skippedGames;
}
