// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `get_components_for_category`, `get_history`, `select_index_with_ring_buffer`, `time_seed`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `CommentaryComponents`

void resetCommentaryHistoryRust() =>
    RustLib.instance.api.crateApiCommentaryResetCommentaryHistoryRust();

String selectCommentaryTemplateRust({
  required String quality,
  required String previousQuality,
  required String gamePhase,
  required double evalDiff,
  required bool hasFork,
  required bool hasPin,
  required bool hasHanging,
}) => RustLib.instance.api.crateApiCommentarySelectCommentaryTemplateRust(
  quality: quality,
  previousQuality: previousQuality,
  gamePhase: gamePhase,
  evalDiff: evalDiff,
  hasFork: hasFork,
  hasPin: hasPin,
  hasHanging: hasHanging,
);
