// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

PositionMetrics evaluatePositionMetrics({
  required String fen,
  required int historyLength,
  required bool isChess960,
}) => RustLib.instance.api.crateApiContextEvaluatePositionMetrics(
  fen: fen,
  historyLength: historyLength,
  isChess960: isChess960,
);

class PositionMetrics {
  final int pieceCount;
  final String gamePhase;

  const PositionMetrics({required this.pieceCount, required this.gamePhase});

  @override
  int get hashCode => pieceCount.hashCode ^ gamePhase.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PositionMetrics &&
          runtimeType == other.runtimeType &&
          pieceCount == other.pieceCount &&
          gamePhase == other.gamePhase;
}
