// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

List<String> getSanHistory({
  required String initialFen,
  required List<String> uciMoves,
  required bool isChess960,
}) => RustLib.instance.api.crateApiHistoryGetSanHistory(
  initialFen: initialFen,
  uciMoves: uciMoves,
  isChess960: isChess960,
);
