// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `attacks_high_value_piece`, `is_closed_file`, `is_endgame`, `is_open_file`, `restricts_opponent_mobility`, `simple_hash`

String selectPersonaMoveRust({
  required String fen,
  required List<PersonaCandidate> candidates,
  required String avatarName,
  required bool isChess960,
  required int moveCount,
}) => RustLib.instance.api.crateApiPersonaSelectPersonaMoveRust(
  fen: fen,
  candidates: candidates,
  avatarName: avatarName,
  isChess960: isChess960,
  moveCount: moveCount,
);

class PersonaCandidate {
  final String uciMove;
  final double evaluation;

  const PersonaCandidate({required this.uciMove, required this.evaluation});

  @override
  int get hashCode => uciMove.hashCode ^ evaluation.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PersonaCandidate &&
          runtimeType == other.runtimeType &&
          uciMove == other.uciMove &&
          evaluation == other.evaluation;
}
