// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `attacks_high_value_piece`, `is_closed_file`, `is_endgame`, `is_open_file`, `restricts_opponent_mobility`, `shakmaty_move_to_uci`, `simple_hash`

PersonaConfig getPersonaConfig({required String avatarName}) => RustLib
    .instance
    .api
    .crateApiPersonaGetPersonaConfig(avatarName: avatarName);

String selectPersonaMoveRust({
  required String fen,
  required List<PersonaCandidate> candidates,
  required String avatarName,
  required bool isChess960,
  required int moveCount,
}) => RustLib.instance.api.crateApiPersonaSelectPersonaMoveRust(
  fen: fen,
  candidates: candidates,
  avatarName: avatarName,
  isChess960: isChess960,
  moveCount: moveCount,
);

class PersonaCandidate {
  final String uciMove;
  final double evaluation;

  const PersonaCandidate({required this.uciMove, required this.evaluation});

  @override
  int get hashCode => uciMove.hashCode ^ evaluation.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PersonaCandidate &&
          runtimeType == other.runtimeType &&
          uciMove == other.uciMove &&
          evaluation == other.evaluation;
}

class PersonaConfig {
  final int multiPv;
  final int skillLevel;
  final int depth;

  const PersonaConfig({
    required this.multiPv,
    required this.skillLevel,
    required this.depth,
  });

  @override
  int get hashCode => multiPv.hashCode ^ skillLevel.hashCode ^ depth.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PersonaConfig &&
          runtimeType == other.runtimeType &&
          multiPv == other.multiPv &&
          skillLevel == other.skillLevel &&
          depth == other.depth;
}
