// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `build_game_record`, `parse_header_line`

List<PgnGameRecord> parsePgnDatabase({required String pgnText}) =>
    RustLib.instance.api.crateApiPgnDbParsePgnDatabase(pgnText: pgnText);

String exportPgnWithHeaders({
  required PgnGameHeader header,
  required String annotatedPgn,
}) => RustLib.instance.api.crateApiPgnDbExportPgnWithHeaders(
  header: header,
  annotatedPgn: annotatedPgn,
);

(String, String) classifyOpeningEco({required List<String> movesSan}) =>
    RustLib.instance.api.crateApiPgnDbClassifyOpeningEco(movesSan: movesSan);

bool saveStudyToDb({required String dbPath, required PgnGameRecord game}) =>
    RustLib.instance.api.crateApiPgnDbSaveStudyToDb(dbPath: dbPath, game: game);

List<PgnGameRecord> loadStudiesFromDb({required String dbPath}) =>
    RustLib.instance.api.crateApiPgnDbLoadStudiesFromDb(dbPath: dbPath);

bool clearAllStudies({required String dbPath}) =>
    RustLib.instance.api.crateApiPgnDbClearAllStudies(dbPath: dbPath);

bool saveGameToDb({
  required String dbPath,
  required String id,
  required String savedAt,
  required String jsonData,
}) => RustLib.instance.api.crateApiPgnDbSaveGameToDb(
  dbPath: dbPath,
  id: id,
  savedAt: savedAt,
  jsonData: jsonData,
);

List<String> loadAllGamesFromDb({required String dbPath}) =>
    RustLib.instance.api.crateApiPgnDbLoadAllGamesFromDb(dbPath: dbPath);

bool deleteGameFromDb({required String dbPath, required String id}) =>
    RustLib.instance.api.crateApiPgnDbDeleteGameFromDb(dbPath: dbPath, id: id);

bool clearAllGames({required String dbPath}) =>
    RustLib.instance.api.crateApiPgnDbClearAllGames(dbPath: dbPath);

class PgnGameHeader {
  final String event;
  final String site;
  final String date;
  final String white;
  final String black;
  final int? whiteElo;
  final int? blackElo;
  final String result;
  final String eco;
  final String opening;

  const PgnGameHeader({
    required this.event,
    required this.site,
    required this.date,
    required this.white,
    required this.black,
    this.whiteElo,
    this.blackElo,
    required this.result,
    required this.eco,
    required this.opening,
  });

  @override
  int get hashCode =>
      event.hashCode ^
      site.hashCode ^
      date.hashCode ^
      white.hashCode ^
      black.hashCode ^
      whiteElo.hashCode ^
      blackElo.hashCode ^
      result.hashCode ^
      eco.hashCode ^
      opening.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PgnGameHeader &&
          runtimeType == other.runtimeType &&
          event == other.event &&
          site == other.site &&
          date == other.date &&
          white == other.white &&
          black == other.black &&
          whiteElo == other.whiteElo &&
          blackElo == other.blackElo &&
          result == other.result &&
          eco == other.eco &&
          opening == other.opening;
}

class PgnGameRecord {
  final PgnGameHeader header;
  final String movesPgn;
  final BigInt index;

  const PgnGameRecord({
    required this.header,
    required this.movesPgn,
    required this.index,
  });

  @override
  int get hashCode => header.hashCode ^ movesPgn.hashCode ^ index.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PgnGameRecord &&
          runtimeType == other.runtimeType &&
          header == other.header &&
          movesPgn == other.movesPgn &&
          index == other.index;
}
