// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

Future<List<Puzzle>> searchPuzzles({
  required String dbPath,
  String? theme,
  int? minRating,
  int? maxRating,
  int? limit,
}) => RustLib.instance.api.crateApiPuzzlesSearchPuzzles(
  dbPath: dbPath,
  theme: theme,
  minRating: minRating,
  maxRating: maxRating,
  limit: limit,
);

Future<Puzzle?> getRandomPuzzle({
  required String dbPath,
  int? minRating,
  int? maxRating,
}) => RustLib.instance.api.crateApiPuzzlesGetRandomPuzzle(
  dbPath: dbPath,
  minRating: minRating,
  maxRating: maxRating,
);

class Puzzle {
  final String id;
  final String fen;
  final List<String> moves;
  final int rating;
  final String themes;

  const Puzzle({
    required this.id,
    required this.fen,
    required this.moves,
    required this.rating,
    required this.themes,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      fen.hashCode ^
      moves.hashCode ^
      rating.hashCode ^
      themes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Puzzle &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          fen == other.fen &&
          moves == other.moves &&
          rating == other.rating &&
          themes == other.themes;
}
