// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

GameTerminationStatus evaluateGameStatus({
  required String fen,
  required bool isChess960,
}) => RustLib.instance.api.crateApiStatusEvaluateGameStatus(
  fen: fen,
  isChess960: isChess960,
);

class GameTerminationStatus {
  final bool isGameOver;
  final bool isCheck;
  final bool isCheckmate;
  final bool isStalemate;
  final bool isInsufficientMaterial;

  const GameTerminationStatus({
    required this.isGameOver,
    required this.isCheck,
    required this.isCheckmate,
    required this.isStalemate,
    required this.isInsufficientMaterial,
  });

  @override
  int get hashCode =>
      isGameOver.hashCode ^
      isCheck.hashCode ^
      isCheckmate.hashCode ^
      isStalemate.hashCode ^
      isInsufficientMaterial.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GameTerminationStatus &&
          runtimeType == other.runtimeType &&
          isGameOver == other.isGameOver &&
          isCheck == other.isCheck &&
          isCheckmate == other.isCheckmate &&
          isStalemate == other.isStalemate &&
          isInsufficientMaterial == other.isInsufficientMaterial;
}
