// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `evaluate_move`, `parse_uci_to_move`, `to_uci`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`, `fmt`

TacticsResult generateTacticsAnalysis({
  required String fen,
  required List<String> userUciMoves,
  required List<StockfishTacticLine> engineAlternatives,
  required bool isChess960,
}) => RustLib.instance.api.crateApiTacticsGenerateTacticsAnalysis(
  fen: fen,
  userUciMoves: userUciMoves,
  engineAlternatives: engineAlternatives,
  isChess960: isChess960,
);

class StockfishTacticLine {
  final String moveUci;
  final double evaluation;
  final List<String> pv;

  const StockfishTacticLine({
    required this.moveUci,
    required this.evaluation,
    required this.pv,
  });

  @override
  int get hashCode => moveUci.hashCode ^ evaluation.hashCode ^ pv.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StockfishTacticLine &&
          runtimeType == other.runtimeType &&
          moveUci == other.moveUci &&
          evaluation == other.evaluation &&
          pv == other.pv;
}

class TacticData {
  final String name;
  final List<String> moves;
  final List<String> sanMoves;
  final String explanation;

  const TacticData({
    required this.name,
    required this.moves,
    required this.sanMoves,
    required this.explanation,
  });

  @override
  int get hashCode =>
      name.hashCode ^ moves.hashCode ^ sanMoves.hashCode ^ explanation.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TacticData &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          moves == other.moves &&
          sanMoves == other.sanMoves &&
          explanation == other.explanation;
}

class TacticsResult {
  final String textResponse;
  final TacticData yourTactic;
  final List<TacticData> alternatives;

  const TacticsResult({
    required this.textResponse,
    required this.yourTactic,
    required this.alternatives,
  });

  @override
  int get hashCode =>
      textResponse.hashCode ^ yourTactic.hashCode ^ alternatives.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TacticsResult &&
          runtimeType == other.runtimeType &&
          textResponse == other.textResponse &&
          yourTactic == other.yourTactic &&
          alternatives == other.alternatives;
}
