// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `format_role_name`

List<String> getThreatenedSquares({
  required String fen,
  required bool isChess960,
}) => RustLib.instance.api.crateApiThreatsGetThreatenedSquares(
  fen: fen,
  isChess960: isChess960,
);

List<String> analyzeTacticalThreats({
  required String fen,
  required bool isChess960,
}) => RustLib.instance.api.crateApiThreatsAnalyzeTacticalThreats(
  fen: fen,
  isChess960: isChess960,
);
