// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

#![allow(
    non_camel_case_types,
    unused,
    non_snake_case,
    clippy::needless_return,
    clippy::redundant_closure_call,
    clippy::redundant_closure,
    clippy::useless_conversion,
    clippy::unit_arg,
    clippy::unused_unit,
    clippy::double_parens,
    clippy::let_and_return,
    clippy::too_many_arguments,
    clippy::match_single_binding,
    clippy::clone_on_copy,
    clippy::let_unit_value,
    clippy::deref_addrof,
    clippy::explicit_auto_deref,
    clippy::borrow_deref_ref,
    clippy::uninlined_format_args,
    clippy::needless_borrow
)]

// Section: imports

use flutter_rust_bridge::for_generated::byteorder::{NativeEndian, ReadBytesExt, WriteBytesExt};
use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
use flutter_rust_bridge::{Handler, IntoIntoDart};

// Section: boilerplate

flutter_rust_bridge::frb_generated_boilerplate!(
    default_stream_sink_codec = SseCodec,
    default_rust_opaque = RustOpaqueMoi,
    default_rust_auto_opaque = RustAutoOpaqueMoi,
);
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_VERSION: &str = "2.12.0";
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_CONTENT_HASH: i32 = -1972798024;

// Section: executor

flutter_rust_bridge::frb_generated_default_handler!();

// Section: wire_funcs

fn wire__crate__api__cognitive__analyze_scotoma_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "analyze_scotoma",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_games =
                <Vec<crate::api::cognitive::SavedGameUci>>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok =
                    Result::<_, ()>::Ok(crate::api::cognitive::analyze_scotoma(api_games))?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__threats__analyze_tactical_threats_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "analyze_tactical_threats",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_fen = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok =
                    Result::<_, ()>::Ok(crate::api::threats::analyze_tactical_threats(api_fen))?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__pgn_db__classify_opening_eco_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "classify_opening_eco",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_moves_san = <Vec<String>>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok =
                    Result::<_, ()>::Ok(crate::api::pgn_db::classify_opening_eco(api_moves_san))?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__pgn_db__clear_all_studies_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "clear_all_studies",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_db_path = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok =
                    Result::<_, ()>::Ok(crate::api::pgn_db::clear_all_studies(api_db_path))?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__status__evaluate_game_status_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "evaluate_game_status",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_fen = <String>::sse_decode(&mut deserializer);
            let api_is_chess960 = <bool>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Result::<_, ()>::Ok(crate::api::status::evaluate_game_status(
                    api_fen,
                    api_is_chess960,
                ))?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__context__evaluate_position_metrics_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "evaluate_position_metrics",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_fen = <String>::sse_decode(&mut deserializer);
            let api_history_length = <u32>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Result::<_, ()>::Ok(
                    crate::api::context::evaluate_position_metrics(api_fen, api_history_length),
                )?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__pgn_db__export_pgn_with_headers_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "export_pgn_with_headers",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_header = <crate::api::pgn_db::PgnGameHeader>::sse_decode(&mut deserializer);
            let api_annotated_pgn = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Result::<_, ()>::Ok(crate::api::pgn_db::export_pgn_with_headers(
                    api_header,
                    api_annotated_pgn,
                ))?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__moves__get_legal_destinations_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "get_legal_destinations",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_fen = <String>::sse_decode(&mut deserializer);
            let api_square = <String>::sse_decode(&mut deserializer);
            let api_is_chess960 = <bool>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Result::<_, ()>::Ok(crate::api::moves::get_legal_destinations(
                    api_fen,
                    api_square,
                    api_is_chess960,
                ))?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__puzzles__get_random_puzzle_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "get_random_puzzle",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_db_path = <String>::sse_decode(&mut deserializer);
            let api_min_rating = <Option<i32>>::sse_decode(&mut deserializer);
            let api_max_rating = <Option<i32>>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok = Result::<_, ()>::Ok(crate::api::puzzles::get_random_puzzle(
                        api_db_path,
                        api_min_rating,
                        api_max_rating,
                    ))?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__history__get_san_history_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "get_san_history",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_initial_fen = <String>::sse_decode(&mut deserializer);
            let api_uci_moves = <Vec<String>>::sse_decode(&mut deserializer);
            let api_is_chess960 = <bool>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Result::<_, ()>::Ok(crate::api::history::get_san_history(
                    api_initial_fen,
                    api_uci_moves,
                    api_is_chess960,
                ))?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__threats__get_threatened_squares_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "get_threatened_squares",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_fen = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok =
                    Result::<_, ()>::Ok(crate::api::threats::get_threatened_squares(api_fen))?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__simple__greet_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "greet",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_name = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Result::<_, ()>::Ok(crate::api::simple::greet(api_name))?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__humanizer__humanize_move_rust_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "humanize_move_rust",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_fen_before = <String>::sse_decode(&mut deserializer);
            let api_move_uci = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Result::<_, ()>::Ok(crate::api::humanizer::humanize_move_rust(
                    api_fen_before,
                    api_move_uci,
                ))?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__simple__init_app_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "init_app",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok = Result::<_, ()>::Ok({
                        crate::api::simple::init_app();
                    })?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__pgn_db__load_studies_from_db_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "load_studies_from_db",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_db_path = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok =
                    Result::<_, ()>::Ok(crate::api::pgn_db::load_studies_from_db(api_db_path))?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__pgn_db__parse_pgn_database_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "parse_pgn_database",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_pgn_text = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok =
                    Result::<_, ()>::Ok(crate::api::pgn_db::parse_pgn_database(api_pgn_text))?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__pgn_db__save_study_to_db_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "save_study_to_db",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_db_path = <String>::sse_decode(&mut deserializer);
            let api_game = <crate::api::pgn_db::PgnGameRecord>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Result::<_, ()>::Ok(crate::api::pgn_db::save_study_to_db(
                    api_db_path,
                    api_game,
                ))?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__puzzles__search_puzzles_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "search_puzzles",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_db_path = <String>::sse_decode(&mut deserializer);
            let api_theme = <Option<String>>::sse_decode(&mut deserializer);
            let api_min_rating = <Option<i32>>::sse_decode(&mut deserializer);
            let api_max_rating = <Option<i32>>::sse_decode(&mut deserializer);
            let api_limit = <Option<i32>>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok = Result::<_, ()>::Ok(crate::api::puzzles::search_puzzles(
                        api_db_path,
                        api_theme,
                        api_min_rating,
                        api_max_rating,
                        api_limit,
                    ))?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__chanakya__select_chanakya_move_rust_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "select_chanakya_move_rust",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_fen = <String>::sse_decode(&mut deserializer);
            let api_candidates =
                <Vec<crate::api::chanakya::ChanakyaCandidate>>::sse_decode(&mut deserializer);
            let api_scotoma =
                <crate::api::chanakya::ChanakyaScotoma>::sse_decode(&mut deserializer);
            let api_playstyle =
                <crate::api::chanakya::ChanakyaPlaystyle>::sse_decode(&mut deserializer);
            let api_half_move_count = <i32>::sse_decode(&mut deserializer);
            let api_eval_abs = <f64>::sse_decode(&mut deserializer);
            let api_is_chess960 = <bool>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok =
                    Result::<_, ()>::Ok(crate::api::chanakya::select_chanakya_move_rust(
                        api_fen,
                        api_candidates,
                        api_scotoma,
                        api_playstyle,
                        api_half_move_count,
                        api_eval_abs,
                        api_is_chess960,
                    ))?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__persona__select_persona_move_rust_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "select_persona_move_rust",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_fen = <String>::sse_decode(&mut deserializer);
            let api_candidates =
                <Vec<crate::api::persona::PersonaCandidate>>::sse_decode(&mut deserializer);
            let api_avatar_name = <String>::sse_decode(&mut deserializer);
            let api_is_chess960 = <bool>::sse_decode(&mut deserializer);
            let api_move_count = <i32>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok =
                    Result::<_, ()>::Ok(crate::api::persona::select_persona_move_rust(
                        api_fen,
                        api_candidates,
                        api_avatar_name,
                        api_is_chess960,
                        api_move_count,
                    ))?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__state__validate_and_apply_move_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "validate_and_apply_move",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_current_fen = <String>::sse_decode(&mut deserializer);
            let api_from_str = <String>::sse_decode(&mut deserializer);
            let api_to_str = <String>::sse_decode(&mut deserializer);
            let api_promotion_str = <String>::sse_decode(&mut deserializer);
            let api_is_chess960 = <bool>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Result::<_, ()>::Ok(crate::api::state::validate_and_apply_move(
                    api_current_fen,
                    api_from_str,
                    api_to_str,
                    api_promotion_str,
                    api_is_chess960,
                ))?;
                Ok(output_ok)
            })())
        },
    )
}

// Section: dart2rust

impl SseDecode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <Vec<u8>>::sse_decode(deserializer);
        return String::from_utf8(inner).unwrap();
    }
}

impl SseDecode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap() != 0
    }
}

impl SseDecode for crate::api::chanakya::ChanakyaCandidate {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_uciMove = <String>::sse_decode(deserializer);
        let mut var_evaluation = <f64>::sse_decode(deserializer);
        return crate::api::chanakya::ChanakyaCandidate {
            uci_move: var_uciMove,
            evaluation: var_evaluation,
        };
    }
}

impl SseDecode for crate::api::chanakya::ChanakyaPlaystyle {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_aggression = <f64>::sse_decode(deserializer);
        let mut var_intensity = <f64>::sse_decode(deserializer);
        let mut var_speed = <f64>::sse_decode(deserializer);
        return crate::api::chanakya::ChanakyaPlaystyle {
            aggression: var_aggression,
            intensity: var_intensity,
            speed: var_speed,
        };
    }
}

impl SseDecode for crate::api::chanakya::ChanakyaScotoma {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_diagonalRetreats = <f64>::sse_decode(deserializer);
        let mut var_horizontalSwings = <f64>::sse_decode(deserializer);
        let mut var_knightForks = <f64>::sse_decode(deserializer);
        let mut var_pinnedPieces = <f64>::sse_decode(deserializer);
        let mut var_kingSafety = <f64>::sse_decode(deserializer);
        let mut var_materialGreed = <f64>::sse_decode(deserializer);
        let mut var_tunnelVision = <f64>::sse_decode(deserializer);
        let mut var_timePanic = <f64>::sse_decode(deserializer);
        return crate::api::chanakya::ChanakyaScotoma {
            diagonal_retreats: var_diagonalRetreats,
            horizontal_swings: var_horizontalSwings,
            knight_forks: var_knightForks,
            pinned_pieces: var_pinnedPieces,
            king_safety: var_kingSafety,
            material_greed: var_materialGreed,
            tunnel_vision: var_tunnelVision,
            time_panic: var_timePanic,
        };
    }
}

impl SseDecode for f64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_f64::<NativeEndian>().unwrap()
    }
}

impl SseDecode for crate::api::status::GameTerminationStatus {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_isGameOver = <bool>::sse_decode(deserializer);
        let mut var_isCheck = <bool>::sse_decode(deserializer);
        let mut var_isCheckmate = <bool>::sse_decode(deserializer);
        let mut var_isStalemate = <bool>::sse_decode(deserializer);
        let mut var_isInsufficientMaterial = <bool>::sse_decode(deserializer);
        return crate::api::status::GameTerminationStatus {
            is_game_over: var_isGameOver,
            is_check: var_isCheck,
            is_checkmate: var_isCheckmate,
            is_stalemate: var_isStalemate,
            is_insufficient_material: var_isInsufficientMaterial,
        };
    }
}

impl SseDecode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_i32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for Vec<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<String>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::chanakya::ChanakyaCandidate> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::api::chanakya::ChanakyaCandidate>::sse_decode(
                deserializer,
            ));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::persona::PersonaCandidate> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::api::persona::PersonaCandidate>::sse_decode(
                deserializer,
            ));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::pgn_db::PgnGameRecord> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::api::pgn_db::PgnGameRecord>::sse_decode(
                deserializer,
            ));
        }
        return ans_;
    }
}

impl SseDecode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<u8>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::puzzles::Puzzle> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::api::puzzles::Puzzle>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::cognitive::SavedGameUci> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::api::cognitive::SavedGameUci>::sse_decode(
                deserializer,
            ));
        }
        return ans_;
    }
}

impl SseDecode for Option<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<String>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<i32> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<i32>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<crate::api::puzzles::Puzzle> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<crate::api::puzzles::Puzzle>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for crate::api::persona::PersonaCandidate {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_uciMove = <String>::sse_decode(deserializer);
        let mut var_evaluation = <f64>::sse_decode(deserializer);
        return crate::api::persona::PersonaCandidate {
            uci_move: var_uciMove,
            evaluation: var_evaluation,
        };
    }
}

impl SseDecode for crate::api::pgn_db::PgnGameHeader {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_event = <String>::sse_decode(deserializer);
        let mut var_site = <String>::sse_decode(deserializer);
        let mut var_date = <String>::sse_decode(deserializer);
        let mut var_white = <String>::sse_decode(deserializer);
        let mut var_black = <String>::sse_decode(deserializer);
        let mut var_whiteElo = <Option<i32>>::sse_decode(deserializer);
        let mut var_blackElo = <Option<i32>>::sse_decode(deserializer);
        let mut var_result = <String>::sse_decode(deserializer);
        let mut var_eco = <String>::sse_decode(deserializer);
        let mut var_opening = <String>::sse_decode(deserializer);
        return crate::api::pgn_db::PgnGameHeader {
            event: var_event,
            site: var_site,
            date: var_date,
            white: var_white,
            black: var_black,
            white_elo: var_whiteElo,
            black_elo: var_blackElo,
            result: var_result,
            eco: var_eco,
            opening: var_opening,
        };
    }
}

impl SseDecode for crate::api::pgn_db::PgnGameRecord {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_header = <crate::api::pgn_db::PgnGameHeader>::sse_decode(deserializer);
        let mut var_movesPgn = <String>::sse_decode(deserializer);
        let mut var_index = <usize>::sse_decode(deserializer);
        return crate::api::pgn_db::PgnGameRecord {
            header: var_header,
            moves_pgn: var_movesPgn,
            index: var_index,
        };
    }
}

impl SseDecode for crate::api::context::PositionMetrics {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_pieceCount = <u32>::sse_decode(deserializer);
        let mut var_gamePhase = <String>::sse_decode(deserializer);
        return crate::api::context::PositionMetrics {
            piece_count: var_pieceCount,
            game_phase: var_gamePhase,
        };
    }
}

impl SseDecode for crate::api::puzzles::Puzzle {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_id = <String>::sse_decode(deserializer);
        let mut var_fen = <String>::sse_decode(deserializer);
        let mut var_moves = <Vec<String>>::sse_decode(deserializer);
        let mut var_rating = <i32>::sse_decode(deserializer);
        let mut var_themes = <String>::sse_decode(deserializer);
        return crate::api::puzzles::Puzzle {
            id: var_id,
            fen: var_fen,
            moves: var_moves,
            rating: var_rating,
            themes: var_themes,
        };
    }
}

impl SseDecode for (String, String) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_field0 = <String>::sse_decode(deserializer);
        let mut var_field1 = <String>::sse_decode(deserializer);
        return (var_field0, var_field1);
    }
}

impl SseDecode for crate::api::cognitive::SavedGameUci {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_recentMoves = <Vec<String>>::sse_decode(deserializer);
        let mut var_isPlayerWhite = <bool>::sse_decode(deserializer);
        let mut var_result = <String>::sse_decode(deserializer);
        let mut var_whiteTimeLeftMs = <i32>::sse_decode(deserializer);
        let mut var_blackTimeLeftMs = <i32>::sse_decode(deserializer);
        let mut var_ratingCategory = <String>::sse_decode(deserializer);
        return crate::api::cognitive::SavedGameUci {
            recent_moves: var_recentMoves,
            is_player_white: var_isPlayerWhite,
            result: var_result,
            white_time_left_ms: var_whiteTimeLeftMs,
            black_time_left_ms: var_blackTimeLeftMs,
            rating_category: var_ratingCategory,
        };
    }
}

impl SseDecode for crate::api::cognitive::ScotomaResult {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_diagonalRetreats = <f64>::sse_decode(deserializer);
        let mut var_horizontalSwings = <f64>::sse_decode(deserializer);
        let mut var_knightForks = <f64>::sse_decode(deserializer);
        let mut var_timePanic = <f64>::sse_decode(deserializer);
        let mut var_materialGreed = <f64>::sse_decode(deserializer);
        let mut var_tunnelVision = <f64>::sse_decode(deserializer);
        let mut var_pinnedPieces = <f64>::sse_decode(deserializer);
        let mut var_kingSafety = <f64>::sse_decode(deserializer);
        return crate::api::cognitive::ScotomaResult {
            diagonal_retreats: var_diagonalRetreats,
            horizontal_swings: var_horizontalSwings,
            knight_forks: var_knightForks,
            time_panic: var_timePanic,
            material_greed: var_materialGreed,
            tunnel_vision: var_tunnelVision,
            pinned_pieces: var_pinnedPieces,
            king_safety: var_kingSafety,
        };
    }
}

impl SseDecode for u32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap()
    }
}

impl SseDecode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {}
}

impl SseDecode for usize {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u64::<NativeEndian>().unwrap() as _
    }
}

fn pde_ffi_dispatcher_primary_impl(
    func_id: i32,
    port: flutter_rust_bridge::for_generated::MessagePort,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        9 => wire__crate__api__puzzles__get_random_puzzle_impl(port, ptr, rust_vec_len, data_len),
        14 => wire__crate__api__simple__init_app_impl(port, ptr, rust_vec_len, data_len),
        18 => wire__crate__api__puzzles__search_puzzles_impl(port, ptr, rust_vec_len, data_len),
        _ => unreachable!(),
    }
}

fn pde_ffi_dispatcher_sync_impl(
    func_id: i32,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        1 => wire__crate__api__cognitive__analyze_scotoma_impl(ptr, rust_vec_len, data_len),
        2 => wire__crate__api__threats__analyze_tactical_threats_impl(ptr, rust_vec_len, data_len),
        3 => wire__crate__api__pgn_db__classify_opening_eco_impl(ptr, rust_vec_len, data_len),
        4 => wire__crate__api__pgn_db__clear_all_studies_impl(ptr, rust_vec_len, data_len),
        5 => wire__crate__api__status__evaluate_game_status_impl(ptr, rust_vec_len, data_len),
        6 => wire__crate__api__context__evaluate_position_metrics_impl(ptr, rust_vec_len, data_len),
        7 => wire__crate__api__pgn_db__export_pgn_with_headers_impl(ptr, rust_vec_len, data_len),
        8 => wire__crate__api__moves__get_legal_destinations_impl(ptr, rust_vec_len, data_len),
        10 => wire__crate__api__history__get_san_history_impl(ptr, rust_vec_len, data_len),
        11 => wire__crate__api__threats__get_threatened_squares_impl(ptr, rust_vec_len, data_len),
        12 => wire__crate__api__simple__greet_impl(ptr, rust_vec_len, data_len),
        13 => wire__crate__api__humanizer__humanize_move_rust_impl(ptr, rust_vec_len, data_len),
        15 => wire__crate__api__pgn_db__load_studies_from_db_impl(ptr, rust_vec_len, data_len),
        16 => wire__crate__api__pgn_db__parse_pgn_database_impl(ptr, rust_vec_len, data_len),
        17 => wire__crate__api__pgn_db__save_study_to_db_impl(ptr, rust_vec_len, data_len),
        19 => {
            wire__crate__api__chanakya__select_chanakya_move_rust_impl(ptr, rust_vec_len, data_len)
        }
        20 => wire__crate__api__persona__select_persona_move_rust_impl(ptr, rust_vec_len, data_len),
        21 => wire__crate__api__state__validate_and_apply_move_impl(ptr, rust_vec_len, data_len),
        _ => unreachable!(),
    }
}

// Section: rust2dart

// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::chanakya::ChanakyaCandidate {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.uci_move.into_into_dart().into_dart(),
            self.evaluation.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::chanakya::ChanakyaCandidate
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::chanakya::ChanakyaCandidate>
    for crate::api::chanakya::ChanakyaCandidate
{
    fn into_into_dart(self) -> crate::api::chanakya::ChanakyaCandidate {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::chanakya::ChanakyaPlaystyle {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.aggression.into_into_dart().into_dart(),
            self.intensity.into_into_dart().into_dart(),
            self.speed.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::chanakya::ChanakyaPlaystyle
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::chanakya::ChanakyaPlaystyle>
    for crate::api::chanakya::ChanakyaPlaystyle
{
    fn into_into_dart(self) -> crate::api::chanakya::ChanakyaPlaystyle {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::chanakya::ChanakyaScotoma {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.diagonal_retreats.into_into_dart().into_dart(),
            self.horizontal_swings.into_into_dart().into_dart(),
            self.knight_forks.into_into_dart().into_dart(),
            self.pinned_pieces.into_into_dart().into_dart(),
            self.king_safety.into_into_dart().into_dart(),
            self.material_greed.into_into_dart().into_dart(),
            self.tunnel_vision.into_into_dart().into_dart(),
            self.time_panic.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::chanakya::ChanakyaScotoma
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::chanakya::ChanakyaScotoma>
    for crate::api::chanakya::ChanakyaScotoma
{
    fn into_into_dart(self) -> crate::api::chanakya::ChanakyaScotoma {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::status::GameTerminationStatus {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.is_game_over.into_into_dart().into_dart(),
            self.is_check.into_into_dart().into_dart(),
            self.is_checkmate.into_into_dart().into_dart(),
            self.is_stalemate.into_into_dart().into_dart(),
            self.is_insufficient_material.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::status::GameTerminationStatus
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::status::GameTerminationStatus>
    for crate::api::status::GameTerminationStatus
{
    fn into_into_dart(self) -> crate::api::status::GameTerminationStatus {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::persona::PersonaCandidate {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.uci_move.into_into_dart().into_dart(),
            self.evaluation.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::persona::PersonaCandidate
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::persona::PersonaCandidate>
    for crate::api::persona::PersonaCandidate
{
    fn into_into_dart(self) -> crate::api::persona::PersonaCandidate {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::pgn_db::PgnGameHeader {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.event.into_into_dart().into_dart(),
            self.site.into_into_dart().into_dart(),
            self.date.into_into_dart().into_dart(),
            self.white.into_into_dart().into_dart(),
            self.black.into_into_dart().into_dart(),
            self.white_elo.into_into_dart().into_dart(),
            self.black_elo.into_into_dart().into_dart(),
            self.result.into_into_dart().into_dart(),
            self.eco.into_into_dart().into_dart(),
            self.opening.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::pgn_db::PgnGameHeader
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::pgn_db::PgnGameHeader>
    for crate::api::pgn_db::PgnGameHeader
{
    fn into_into_dart(self) -> crate::api::pgn_db::PgnGameHeader {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::pgn_db::PgnGameRecord {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.header.into_into_dart().into_dart(),
            self.moves_pgn.into_into_dart().into_dart(),
            self.index.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::pgn_db::PgnGameRecord
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::pgn_db::PgnGameRecord>
    for crate::api::pgn_db::PgnGameRecord
{
    fn into_into_dart(self) -> crate::api::pgn_db::PgnGameRecord {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::context::PositionMetrics {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.piece_count.into_into_dart().into_dart(),
            self.game_phase.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::context::PositionMetrics
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::context::PositionMetrics>
    for crate::api::context::PositionMetrics
{
    fn into_into_dart(self) -> crate::api::context::PositionMetrics {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::puzzles::Puzzle {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.id.into_into_dart().into_dart(),
            self.fen.into_into_dart().into_dart(),
            self.moves.into_into_dart().into_dart(),
            self.rating.into_into_dart().into_dart(),
            self.themes.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::puzzles::Puzzle {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::puzzles::Puzzle>
    for crate::api::puzzles::Puzzle
{
    fn into_into_dart(self) -> crate::api::puzzles::Puzzle {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::cognitive::SavedGameUci {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.recent_moves.into_into_dart().into_dart(),
            self.is_player_white.into_into_dart().into_dart(),
            self.result.into_into_dart().into_dart(),
            self.white_time_left_ms.into_into_dart().into_dart(),
            self.black_time_left_ms.into_into_dart().into_dart(),
            self.rating_category.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::cognitive::SavedGameUci
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::cognitive::SavedGameUci>
    for crate::api::cognitive::SavedGameUci
{
    fn into_into_dart(self) -> crate::api::cognitive::SavedGameUci {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::cognitive::ScotomaResult {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.diagonal_retreats.into_into_dart().into_dart(),
            self.horizontal_swings.into_into_dart().into_dart(),
            self.knight_forks.into_into_dart().into_dart(),
            self.time_panic.into_into_dart().into_dart(),
            self.material_greed.into_into_dart().into_dart(),
            self.tunnel_vision.into_into_dart().into_dart(),
            self.pinned_pieces.into_into_dart().into_dart(),
            self.king_safety.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::cognitive::ScotomaResult
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::cognitive::ScotomaResult>
    for crate::api::cognitive::ScotomaResult
{
    fn into_into_dart(self) -> crate::api::cognitive::ScotomaResult {
        self
    }
}

impl SseEncode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<u8>>::sse_encode(self.into_bytes(), serializer);
    }
}

impl SseEncode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self as _).unwrap();
    }
}

impl SseEncode for crate::api::chanakya::ChanakyaCandidate {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.uci_move, serializer);
        <f64>::sse_encode(self.evaluation, serializer);
    }
}

impl SseEncode for crate::api::chanakya::ChanakyaPlaystyle {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <f64>::sse_encode(self.aggression, serializer);
        <f64>::sse_encode(self.intensity, serializer);
        <f64>::sse_encode(self.speed, serializer);
    }
}

impl SseEncode for crate::api::chanakya::ChanakyaScotoma {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <f64>::sse_encode(self.diagonal_retreats, serializer);
        <f64>::sse_encode(self.horizontal_swings, serializer);
        <f64>::sse_encode(self.knight_forks, serializer);
        <f64>::sse_encode(self.pinned_pieces, serializer);
        <f64>::sse_encode(self.king_safety, serializer);
        <f64>::sse_encode(self.material_greed, serializer);
        <f64>::sse_encode(self.tunnel_vision, serializer);
        <f64>::sse_encode(self.time_panic, serializer);
    }
}

impl SseEncode for f64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_f64::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for crate::api::status::GameTerminationStatus {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_game_over, serializer);
        <bool>::sse_encode(self.is_check, serializer);
        <bool>::sse_encode(self.is_checkmate, serializer);
        <bool>::sse_encode(self.is_stalemate, serializer);
        <bool>::sse_encode(self.is_insufficient_material, serializer);
    }
}

impl SseEncode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_i32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for Vec<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <String>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::chanakya::ChanakyaCandidate> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::chanakya::ChanakyaCandidate>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::persona::PersonaCandidate> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::persona::PersonaCandidate>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::pgn_db::PgnGameRecord> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::pgn_db::PgnGameRecord>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <u8>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::puzzles::Puzzle> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::puzzles::Puzzle>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::cognitive::SavedGameUci> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::cognitive::SavedGameUci>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Option<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <String>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<i32> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <i32>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<crate::api::puzzles::Puzzle> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <crate::api::puzzles::Puzzle>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for crate::api::persona::PersonaCandidate {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.uci_move, serializer);
        <f64>::sse_encode(self.evaluation, serializer);
    }
}

impl SseEncode for crate::api::pgn_db::PgnGameHeader {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.event, serializer);
        <String>::sse_encode(self.site, serializer);
        <String>::sse_encode(self.date, serializer);
        <String>::sse_encode(self.white, serializer);
        <String>::sse_encode(self.black, serializer);
        <Option<i32>>::sse_encode(self.white_elo, serializer);
        <Option<i32>>::sse_encode(self.black_elo, serializer);
        <String>::sse_encode(self.result, serializer);
        <String>::sse_encode(self.eco, serializer);
        <String>::sse_encode(self.opening, serializer);
    }
}

impl SseEncode for crate::api::pgn_db::PgnGameRecord {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <crate::api::pgn_db::PgnGameHeader>::sse_encode(self.header, serializer);
        <String>::sse_encode(self.moves_pgn, serializer);
        <usize>::sse_encode(self.index, serializer);
    }
}

impl SseEncode for crate::api::context::PositionMetrics {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <u32>::sse_encode(self.piece_count, serializer);
        <String>::sse_encode(self.game_phase, serializer);
    }
}

impl SseEncode for crate::api::puzzles::Puzzle {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.id, serializer);
        <String>::sse_encode(self.fen, serializer);
        <Vec<String>>::sse_encode(self.moves, serializer);
        <i32>::sse_encode(self.rating, serializer);
        <String>::sse_encode(self.themes, serializer);
    }
}

impl SseEncode for (String, String) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.0, serializer);
        <String>::sse_encode(self.1, serializer);
    }
}

impl SseEncode for crate::api::cognitive::SavedGameUci {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<String>>::sse_encode(self.recent_moves, serializer);
        <bool>::sse_encode(self.is_player_white, serializer);
        <String>::sse_encode(self.result, serializer);
        <i32>::sse_encode(self.white_time_left_ms, serializer);
        <i32>::sse_encode(self.black_time_left_ms, serializer);
        <String>::sse_encode(self.rating_category, serializer);
    }
}

impl SseEncode for crate::api::cognitive::ScotomaResult {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <f64>::sse_encode(self.diagonal_retreats, serializer);
        <f64>::sse_encode(self.horizontal_swings, serializer);
        <f64>::sse_encode(self.knight_forks, serializer);
        <f64>::sse_encode(self.time_panic, serializer);
        <f64>::sse_encode(self.material_greed, serializer);
        <f64>::sse_encode(self.tunnel_vision, serializer);
        <f64>::sse_encode(self.pinned_pieces, serializer);
        <f64>::sse_encode(self.king_safety, serializer);
    }
}

impl SseEncode for u32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self).unwrap();
    }
}

impl SseEncode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {}
}

impl SseEncode for usize {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer
            .cursor
            .write_u64::<NativeEndian>(self as _)
            .unwrap();
    }
}

#[cfg(not(target_family = "wasm"))]
mod io {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.12.0.

    // Section: imports

    use super::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_io!();
}
#[cfg(not(target_family = "wasm"))]
pub use io::*;

/// cbindgen:ignore
#[cfg(target_family = "wasm")]
mod web {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.12.0.

    // Section: imports

    use super::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::wasm_bindgen;
    use flutter_rust_bridge::for_generated::wasm_bindgen::prelude::*;
    use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_web!();
}
#[cfg(target_family = "wasm")]
pub use web::*;
